[{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5504","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5504/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5504/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5504/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5504","id":1185965655,"node_id":"I_kwDOCBuapc5GsGZX","number":5504,"title":"Pretrain red yellow masks","user":{"login":"canfiliz","id":5403406,"node_id":"MDQ6VXNlcjU0MDM0MDY=","avatar_url":"https://avatars.githubusercontent.com/u/5403406?v=4","gravatar_id":"","url":"https://api.github.com/users/canfiliz","html_url":"https://github.com/canfiliz","followers_url":"https://api.github.com/users/canfiliz/followers","following_url":"https://api.github.com/users/canfiliz/following{/other_user}","gists_url":"https://api.github.com/users/canfiliz/gists{/gist_id}","starred_url":"https://api.github.com/users/canfiliz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/canfiliz/subscriptions","organizations_url":"https://api.github.com/users/canfiliz/orgs","repos_url":"https://api.github.com/users/canfiliz/repos","events_url":"https://api.github.com/users/canfiliz/events{/privacy}","received_events_url":"https://api.github.com/users/canfiliz/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-30T06:43:28Z","updated_at":"2022-03-30T06:43:28Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"I train model with colab latest ver in pretrain for a week then close pretrain and train normally but i see red yellow masks in traning preview why?","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5504/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5504/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5503","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5503/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5503/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5503/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5503","id":1183982339,"node_id":"I_kwDOCBuapc5GkiMD","number":5503,"title":"Face doesn't merge :( ","user":{"login":"Ketaminzzz","id":101893376,"node_id":"U_kgDOBhLFAA","avatar_url":"https://avatars.githubusercontent.com/u/101893376?v=4","gravatar_id":"","url":"https://api.github.com/users/Ketaminzzz","html_url":"https://github.com/Ketaminzzz","followers_url":"https://api.github.com/users/Ketaminzzz/followers","following_url":"https://api.github.com/users/Ketaminzzz/following{/other_user}","gists_url":"https://api.github.com/users/Ketaminzzz/gists{/gist_id}","starred_url":"https://api.github.com/users/Ketaminzzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Ketaminzzz/subscriptions","organizations_url":"https://api.github.com/users/Ketaminzzz/orgs","repos_url":"https://api.github.com/users/Ketaminzzz/repos","events_url":"https://api.github.com/users/Ketaminzzz/events{/privacy}","received_events_url":"https://api.github.com/users/Ketaminzzz/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-28T20:56:17Z","updated_at":"2022-03-28T20:56:17Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"I used Train SAEHD  to train upto 95k iterations but after hitting “merged to mp4” I just get same video without any face swapped at all. The training and merging process went great without any errors. ( merged_mask show a black screen ) \r\n\r\nPlease if anybody has solution to this issue, help me. Thanks.\r\n![data_dst 29_3_2022 3_53_39 AM](https://user-images.githubusercontent.com/101893376/160485571-65578980-101f-473e-a97b-69c18bf9fbe9.png)\r\n\r\n","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5503/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5503/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5502","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5502/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5502/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5502/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5502","id":1183692236,"node_id":"I_kwDOCBuapc5GjbXM","number":5502,"title":"Can't get RTX 3090 to work with deepfacelab.","user":{"login":"diegito55","id":73799980,"node_id":"MDQ6VXNlcjczNzk5OTgw","avatar_url":"https://avatars.githubusercontent.com/u/73799980?v=4","gravatar_id":"","url":"https://api.github.com/users/diegito55","html_url":"https://github.com/diegito55","followers_url":"https://api.github.com/users/diegito55/followers","following_url":"https://api.github.com/users/diegito55/following{/other_user}","gists_url":"https://api.github.com/users/diegito55/gists{/gist_id}","starred_url":"https://api.github.com/users/diegito55/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/diegito55/subscriptions","organizations_url":"https://api.github.com/users/diegito55/orgs","repos_url":"https://api.github.com/users/diegito55/repos","events_url":"https://api.github.com/users/diegito55/events{/privacy}","received_events_url":"https://api.github.com/users/diegito55/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-28T16:32:52Z","updated_at":"2022-03-28T16:34:29Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS\r\nPOST ONLY ISSUES RELATED TO BUGS OR CODE\r\n\r\n## Expected behavior\r\n\r\nI have the highest specs with an rtx 3090 and a ryzen 5800x cpu. I expect it to run, but it comes up with this error:Error: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[5376,34,34] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[node Pad_38 (defined at C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py:87) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_4/concat/_1141]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[5376,34,34] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[node Pad_38 (defined at C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py:87) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nErrors may have originated from an input operation.\r\nInput Source operations connected to node Pad_38:\r\n LeakyRelu_28 (defined at C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py:29)\r\n\r\nInput Source operations connected to node Pad_38:\r\n LeakyRelu_28 (defined at C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py:29)\r\n\r\nOriginal stack trace for 'Pad_38':\r\n  File \"threading.py\", line 884, in _bootstrap\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 58, in trainerThread\r\n    debug=debug)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 193, in __init__\r\n    self.on_initialize()\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 410, in on_initialize\r\n    gpu_pred_dst_dst, gpu_pred_dst_dstm = self.decoder_dst(gpu_dst_code)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 225, in forward\r\n    x = self.upscale2(x)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 71, in forward\r\n    x = self.conv1(x)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\LayerBase.py\", line 14, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py\", line 87, in forward\r\n    x = tf.pad (x, padding, mode='CONSTANT')\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 206, in wrapper\r\n    return target(*args, **kwargs)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\array_ops.py\", line 3528, in pad\r\n    result = gen_array_ops.pad(tensor, paddings, name=name)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\gen_array_ops.py\", line 6487, in pad\r\n    \"Pad\", input=input, paddings=paddings, name=name)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 750, in _apply_op_helper\r\n    attrs=attr_protos, op_def=op_def)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3569, in _create_op_internal\r\n    op_def=op_def)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2045, in __init__\r\n    self._traceback = tf_stack.extract_stack_for_node(self._c_op)\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1375, in _do_call\r\n    return fn(*args)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1360, in _run_fn\r\n    target_list, run_metadata)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1453, in _call_tf_sessionrun\r\n    run_metadata)\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[5376,34,34] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[{{node Pad_38}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_4/concat/_1141]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[5376,34,34] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[{{node Pad_38}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 129, in trainerThread\r\n    iter, iter_time = model.train_one_iter()\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 474, in train_one_iter\r\n    losses = self.onTrainOneIter()\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 774, in onTrainOneIter\r\n    src_loss, dst_loss = self.src_dst_train (warped_src, target_src, target_srcm, target_srcm_em, warped_dst, target_dst, target_dstm, target_dstm_em)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 584, in src_dst_train\r\n    self.target_dstm_em:target_dstm_em,\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\r\n    run_metadata_ptr)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1191, in _run\r\n    feed_dict_tensor, options, run_metadata)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1369, in _do_run\r\n    run_metadata)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1394, in _do_call\r\n    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[5376,34,34] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[node Pad_38 (defined at C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py:87) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_4/concat/_1141]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[5376,34,34] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[node Pad_38 (defined at C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py:87) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nErrors may have originated from an input operation.\r\nInput Source operations connected to node Pad_38:\r\n LeakyRelu_28 (defined at C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py:29)\r\n\r\nInput Source operations connected to node Pad_38:\r\n LeakyRelu_28 (defined at C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py:29)\r\n\r\nOriginal stack trace for 'Pad_38':\r\n  File \"threading.py\", line 884, in _bootstrap\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 58, in trainerThread\r\n    debug=debug)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 193, in __init__\r\n    self.on_initialize()\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 410, in on_initialize\r\n    gpu_pred_dst_dst, gpu_pred_dst_dstm = self.decoder_dst(gpu_dst_code)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 225, in forward\r\n    x = self.upscale2(x)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 71, in forward\r\n    x = self.conv1(x)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\LayerBase.py\", line 14, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py\", line 87, in forward\r\n    x = tf.pad (x, padding, mode='CONSTANT')\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 206, in wrapper\r\n    return target(*args, **kwargs)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\array_ops.py\", line 3528, in pad\r\n    result = gen_array_ops.pad(tensor, paddings, name=name)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\gen_array_ops.py\", line 6487, in pad\r\n    \"Pad\", input=input, paddings=paddings, name=name)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 750, in _apply_op_helper\r\n    attrs=attr_protos, op_def=op_def)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3569, in _create_op_internal\r\n    op_def=op_def)\r\n  File \"C:\\Users\\Redux\\Downloads\\Reface\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2045, in __init__\r\n    self._traceback = tf_stack.extract_stack_for_node(self._c_op) \r\n## Actual behavior\r\nI go through all the settings in SAEHD without changing anything and it comes up with this long paragraph that I can't understand\r\nor it says bad allocation or out of memory.\r\n\r\n## Steps to reproduce\r\n\r\nI cannot recall exactly what i changed but i don't think it would be detrimental because I then used the cpu instead of the gpu and worked fine, but I don't think im getting the quickest result with the cpu.\r\nresolution: 128                     ==\r\n==             face_type: wf                      ==\r\n==     models_opt_on_gpu: True                    ==\r\n==                 archi: df-ud                   ==\r\n==               ae_dims: 256                     ==\r\n==                e_dims: 64                      ==\r\n==                d_dims: 64                      ==\r\n==           d_mask_dims: 22                      ==\r\n==       masked_training: True                    ==\r\n==       eyes_mouth_prio: True                    ==\r\n==           uniform_yaw: True                    ==\r\n==         blur_out_mask: True                    ==\r\n==             adabelief: True                    ==\r\n==            lr_dropout: n                       ==\r\n==           random_warp: False                   ==\r\n==      random_hsv_power: 0.0                     ==\r\n==       true_face_power: 0.0                     ==\r\n==      face_style_power: 0.0                     ==\r\n==        bg_style_power: 0.0                     ==\r\n==               ct_mode: none                    ==\r\n==              clipgrad: True                    ==\r\n==              pretrain: True                    ==\r\n==       autobackup_hour: 1                       ==\r\n== write_preview_history: True                    ==\r\n==           target_iter: 0                       ==\r\n==       random_src_flip: False                   ==\r\n==       random_dst_flip: False                   ==\r\n==            batch_size: 21                      ==\r\n==             gan_power: 0.0                     ==\r\n==        gan_patch_size: 16                      ==\r\n==              gan_dims: 16                      ==\r\n==                                                ==\r\n==------------------ Running On ------------------==\r\n==                                                ==\r\n==          Device index: 0                       ==\r\n==                  Name: NVIDIA GeForce RTX 3090 ==\r\n==                  VRAM: 21.17GB                 ==\r\n==\r\n## Other relevant information\r\n- **Command lined used (if not specified in steps to reproduce)**: main.py ...\r\n- **Operating system and version:** Windows, macOS, Linux \r\n- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5502/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5502/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5499","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5499/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5499/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5499/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5499","id":1176331439,"node_id":"I_kwDOCBuapc5GHWSv","number":5499,"title":"3090 faceset extract is very slow,Is it possible to use chunking and multiple processes for extraction operations?","user":{"login":"deviljoker5200","id":78338803,"node_id":"MDQ6VXNlcjc4MzM4ODAz","avatar_url":"https://avatars.githubusercontent.com/u/78338803?v=4","gravatar_id":"","url":"https://api.github.com/users/deviljoker5200","html_url":"https://github.com/deviljoker5200","followers_url":"https://api.github.com/users/deviljoker5200/followers","following_url":"https://api.github.com/users/deviljoker5200/following{/other_user}","gists_url":"https://api.github.com/users/deviljoker5200/gists{/gist_id}","starred_url":"https://api.github.com/users/deviljoker5200/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/deviljoker5200/subscriptions","organizations_url":"https://api.github.com/users/deviljoker5200/orgs","repos_url":"https://api.github.com/users/deviljoker5200/repos","events_url":"https://api.github.com/users/deviljoker5200/events{/privacy}","received_events_url":"https://api.github.com/users/deviljoker5200/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-22T06:36:30Z","updated_at":"2022-03-22T06:36:30Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"## Expected behavior\r\n\r\nvery fast extract face\r\n\r\n## Actual behavior\r\n\r\nextract face fastest speed is only 2.34it/s\r\n\r\n## Steps to reproduce\r\n\r\ndata_xxx faceset extract.bat\r\n\r\n## Other relevant information\r\n- RTX3090\r\n\r\n\r\nIs it possible to use chunking and multiple processes for extraction operations？","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5499/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5499/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5498","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5498/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5498/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5498/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5498","id":1174550191,"node_id":"I_kwDOCBuapc5GAjav","number":5498,"title":"Wav2lip only with DeepFaceLab","user":{"login":"sktechnology","id":44030773,"node_id":"MDQ6VXNlcjQ0MDMwNzcz","avatar_url":"https://avatars.githubusercontent.com/u/44030773?v=4","gravatar_id":"","url":"https://api.github.com/users/sktechnology","html_url":"https://github.com/sktechnology","followers_url":"https://api.github.com/users/sktechnology/followers","following_url":"https://api.github.com/users/sktechnology/following{/other_user}","gists_url":"https://api.github.com/users/sktechnology/gists{/gist_id}","starred_url":"https://api.github.com/users/sktechnology/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sktechnology/subscriptions","organizations_url":"https://api.github.com/users/sktechnology/orgs","repos_url":"https://api.github.com/users/sktechnology/repos","events_url":"https://api.github.com/users/sktechnology/events{/privacy}","received_events_url":"https://api.github.com/users/sktechnology/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-20T13:36:15Z","updated_at":"2022-03-20T13:36:15Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"hello everyone,\r\n\r\nIs it possible to do only wav2lip with the DeepFaceLab library, if yes, how to do it.\r\n\r\nThank you.","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5498/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5498/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5497","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5497/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5497/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5497/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5497","id":1174236321,"node_id":"I_kwDOCBuapc5F_Wyh","number":5497,"title":"gtx1080TI vs rtx3080","user":{"login":"djchairz","id":101927710,"node_id":"U_kgDOBhNLHg","avatar_url":"https://avatars.githubusercontent.com/u/101927710?v=4","gravatar_id":"","url":"https://api.github.com/users/djchairz","html_url":"https://github.com/djchairz","followers_url":"https://api.github.com/users/djchairz/followers","following_url":"https://api.github.com/users/djchairz/following{/other_user}","gists_url":"https://api.github.com/users/djchairz/gists{/gist_id}","starred_url":"https://api.github.com/users/djchairz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/djchairz/subscriptions","organizations_url":"https://api.github.com/users/djchairz/orgs","repos_url":"https://api.github.com/users/djchairz/repos","events_url":"https://api.github.com/users/djchairz/events{/privacy}","received_events_url":"https://api.github.com/users/djchairz/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-03-19T10:49:20Z","updated_at":"2022-03-20T20:30:52Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hi,\r\n\r\ni've switched computers from an desktop with;\r\nwin10\r\ngtx1080ti gpu\r\namd fx-8379 cpu\r\n16gb memory\r\n\r\nto:\r\nwin11\r\nrtx3080 gpu\r\ni9-12900kf cpu\r\n32gb memory\r\n\r\ni am trying to run model with these settings:\r\n================== Model Summary ===================\r\n==                                                ==\r\n==            Model name: DF-UD384_SAEHD          ==\r\n==                                                ==\r\n==     Current iteration: 561403                  ==\r\n==                                                ==\r\n==---------------- Model Options -----------------==\r\n==                                                ==\r\n==            resolution: 384                     ==\r\n==             face_type: wf                      ==\r\n==     models_opt_on_gpu: True                    ==\r\n==                 archi: df-ud                   ==\r\n==               ae_dims: 352                     ==\r\n==                e_dims: 88                      ==\r\n==                d_dims: 88                      ==\r\n==           d_mask_dims: 16                      ==\r\n==       masked_training: True                    ==\r\n==       eyes_mouth_prio: True                    ==\r\n==           uniform_yaw: False                   ==\r\n==             adabelief: True                    ==\r\n==            lr_dropout: y                       ==\r\n==           random_warp: False                   ==\r\n==       true_face_power: 0.2                     ==\r\n==      face_style_power: 0.0                     ==\r\n==        bg_style_power: 0.0                     ==\r\n==               ct_mode: none                    ==\r\n==              clipgrad: False                   ==\r\n==              pretrain: False                   ==\r\n==       autobackup_hour: 0                       ==\r\n== write_preview_history: False                   ==\r\n==           target_iter: 0                       ==\r\n==       random_src_flip: False                   ==\r\n==       random_dst_flip: True                    ==\r\n==            batch_size: 4                       ==\r\n==             gan_power: 0.0                     ==\r\n==        gan_patch_size: 48                      ==\r\n==              gan_dims: 16                      ==\r\n==         blur_out_mask: False                   ==\r\n==      random_hsv_power: 0.0                     ==\r\n==                                                ==\r\n==------------------ Running On ------------------==\r\n==                                                ==\r\n==          Device index: 0                       ==\r\n==                  Name: NVIDIA GeForce RTX 3080 ==\r\n==                  VRAM: 7.27GB                  ==\r\n==                                                ==\r\n====================================================\r\n\r\n**it has been working fine on the gtx1080ti for over 500k iterations. but wont run on the new rig(rtx3080).**\r\n\r\ngetting following erros:\r\nError: 2 root error(s) found.\r\n  (0) Resource exhausted: failed to allocate memory\r\n         [[node mul_129 (defined at D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:64) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_4/concat/_547]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: failed to allocate memory\r\n         [[node mul_129 (defined at D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:64) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nErrors may have originated from an input operation.\r\nInput Source operations connected to node mul_129:\r\n src_dst_opt/vs_inter/dense2/weight_0/read (defined at D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:38)\r\n\r\nInput Source operations connected to node mul_129:\r\n src_dst_opt/vs_inter/dense2/weight_0/read (defined at D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:38)\r\n\r\nOriginal stack trace for 'mul_129':\r\n  File \"threading.py\", line 884, in _bootstrap\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 58, in trainerThread\r\n    debug=debug)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 193, in __init__\r\n    self.on_initialize()\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 564, in on_initialize\r\n    src_dst_loss_gv_op = self.src_dst_opt.get_update_op (nn.average_gv_list (gpu_G_loss_gvs))\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py\", line 64, in get_update_op\r\n    v_t = self.beta_2*vs + (1.0-self.beta_2) * tf.square(g-m_t)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 1076, in _run_op\r\n    return tensor_oper(a.value(), *args, **kwargs)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 1400, in r_binary_op_wrapper\r\n    return func(x, y, name=name)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 1710, in _mul_dispatch\r\n    return multiply(x, y, name=name)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 206, in wrapper\r\n    return target(*args, **kwargs)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 530, in multiply\r\n    return gen_math_ops.mul(x, y, name)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\gen_math_ops.py\", line 6245, in mul\r\n    \"Mul\", x=x, y=y, name=name)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 750, in _apply_op_helper\r\n    attrs=attr_protos, op_def=op_def)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3569, in _create_op_internal\r\n    op_def=op_def)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2045, in __init__\r\n    self._traceback = tf_stack.extract_stack_for_node(self._c_op)\r\n\r\nTraceback (most recent call last):\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1375, in _do_call\r\n    return fn(*args)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1360, in _run_fn\r\n    target_list, run_metadata)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1453, in _call_tf_sessionrun\r\n    run_metadata)\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.\r\n  (0) Resource exhausted: failed to allocate memory\r\n         [[{{node mul_129}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_4/concat/_547]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: failed to allocate memory\r\n         [[{{node mul_129}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 129, in trainerThread\r\n    iter, iter_time = model.train_one_iter()\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 474, in train_one_iter\r\n    losses = self.onTrainOneIter()\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 774, in onTrainOneIter\r\n    src_loss, dst_loss = self.src_dst_train (warped_src, target_src, target_srcm, target_srcm_em, warped_dst, target_dst, target_dstm, target_dstm_em)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 584, in src_dst_train\r\n    self.target_dstm_em:target_dstm_em,\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\r\n    run_metadata_ptr)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1191, in _run\r\n    feed_dict_tensor, options, run_metadata)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1369, in _do_run\r\n    run_metadata)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1394, in _do_call\r\n    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.\r\n  (0) Resource exhausted: failed to allocate memory\r\n         [[node mul_129 (defined at D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:64) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_4/concat/_547]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: failed to allocate memory\r\n         [[node mul_129 (defined at D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:64) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nErrors may have originated from an input operation.\r\nInput Source operations connected to node mul_129:\r\n src_dst_opt/vs_inter/dense2/weight_0/read (defined at D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:38)\r\n\r\nInput Source operations connected to node mul_129:\r\n src_dst_opt/vs_inter/dense2/weight_0/read (defined at D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:38)\r\n\r\nOriginal stack trace for 'mul_129':\r\n  File \"threading.py\", line 884, in _bootstrap\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 58, in trainerThread\r\n    debug=debug)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 193, in __init__\r\n    self.on_initialize()\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 564, in on_initialize\r\n    src_dst_loss_gv_op = self.src_dst_opt.get_update_op (nn.average_gv_list (gpu_G_loss_gvs))\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py\", line 64, in get_update_op\r\n    v_t = self.beta_2*vs + (1.0-self.beta_2) * tf.square(g-m_t)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 1076, in _run_op\r\n    return tensor_oper(a.value(), *args, **kwargs)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 1400, in r_binary_op_wrapper\r\n    return func(x, y, name=name)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 1710, in _mul_dispatch\r\n    return multiply(x, y, name=name)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 206, in wrapper\r\n    return target(*args, **kwargs)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 530, in multiply\r\n    return gen_math_ops.mul(x, y, name)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\gen_math_ops.py\", line 6245, in mul\r\n    \"Mul\", x=x, y=y, name=name)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 750, in _apply_op_helper\r\n    attrs=attr_protos, op_def=op_def)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3569, in _create_op_internal\r\n    op_def=op_def)\r\n  File \"D:\\New folder\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2045, in __init__\r\n    self._traceback = tf_stack.extract_stack_for_node(self._c_op)\r\n\r\n\r\nAny sugestions?\r\npaging file enabled on 500gb, and hardware accelerated gpu scheduling enabled","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5497/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5497/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5496","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5496/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5496/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5496/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5496","id":1174233191,"node_id":"I_kwDOCBuapc5F_WBn","number":5496,"title":"AMP model on CPU","user":{"login":"andyst75","id":43100339,"node_id":"MDQ6VXNlcjQzMTAwMzM5","avatar_url":"https://avatars.githubusercontent.com/u/43100339?v=4","gravatar_id":"","url":"https://api.github.com/users/andyst75","html_url":"https://github.com/andyst75","followers_url":"https://api.github.com/users/andyst75/followers","following_url":"https://api.github.com/users/andyst75/following{/other_user}","gists_url":"https://api.github.com/users/andyst75/gists{/gist_id}","starred_url":"https://api.github.com/users/andyst75/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/andyst75/subscriptions","organizations_url":"https://api.github.com/users/andyst75/orgs","repos_url":"https://api.github.com/users/andyst75/repos","events_url":"https://api.github.com/users/andyst75/events{/privacy}","received_events_url":"https://api.github.com/users/andyst75/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-19T10:32:18Z","updated_at":"2022-03-19T10:32:18Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Models arch AMP do not run on CPU (station w/o GPU or with param `--cpu-only`).\r\n\r\nTested on Windows 10 / Ubuntu 20.04LTS\r\nTensorflow 2.4, 2.7.1\r\nPython 3.7.11, 3.9.7\r\nLatest DFL version.","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5496/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5496/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5495","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5495/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5495/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5495/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5495","id":1173882367,"node_id":"I_kwDOCBuapc5F-AX_","number":5495,"title":"DeepFaceLab_DirectX12  missing 4 file!","user":{"login":"Ketaminzzz","id":101893376,"node_id":"U_kgDOBhLFAA","avatar_url":"https://avatars.githubusercontent.com/u/101893376?v=4","gravatar_id":"","url":"https://api.github.com/users/Ketaminzzz","html_url":"https://github.com/Ketaminzzz","followers_url":"https://api.github.com/users/Ketaminzzz/followers","following_url":"https://api.github.com/users/Ketaminzzz/following{/other_user}","gists_url":"https://api.github.com/users/Ketaminzzz/gists{/gist_id}","starred_url":"https://api.github.com/users/Ketaminzzz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Ketaminzzz/subscriptions","organizations_url":"https://api.github.com/users/Ketaminzzz/orgs","repos_url":"https://api.github.com/users/Ketaminzzz/repos","events_url":"https://api.github.com/users/Ketaminzzz/events{/privacy}","received_events_url":"https://api.github.com/users/Ketaminzzz/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-03-18T18:20:58Z","updated_at":"2022-03-20T10:12:26Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"DeepFaceLab_DirectX12  missing 4 file ( project.code - python -setenv-vscode ) \r\nHelp me !","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5495/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5495/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5494","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5494/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5494/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5494/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5494","id":1169386734,"node_id":"I_kwDOCBuapc5Fs2zu","number":5494,"title":"What parameters for quick96??","user":{"login":"tyler2269","id":101553297,"node_id":"U_kgDOBg2UkQ","avatar_url":"https://avatars.githubusercontent.com/u/101553297?v=4","gravatar_id":"","url":"https://api.github.com/users/tyler2269","html_url":"https://github.com/tyler2269","followers_url":"https://api.github.com/users/tyler2269/followers","following_url":"https://api.github.com/users/tyler2269/following{/other_user}","gists_url":"https://api.github.com/users/tyler2269/gists{/gist_id}","starred_url":"https://api.github.com/users/tyler2269/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tyler2269/subscriptions","organizations_url":"https://api.github.com/users/tyler2269/orgs","repos_url":"https://api.github.com/users/tyler2269/repos","events_url":"https://api.github.com/users/tyler2269/events{/privacy}","received_events_url":"https://api.github.com/users/tyler2269/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-15T09:12:25Z","updated_at":"2022-03-15T09:12:25Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS\r\nPOST ONLY ISSUES RELATED TO BUGS OR CODE\r\n\r\n## Expected behavior\r\n\r\n*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*\r\n\r\n## Actual behavior\r\n\r\n*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*\r\n\r\n## Steps to reproduce\r\n\r\n*Describe, in some detail, the steps you tried that resulted in the behavior described above.*\r\n\r\n## Other relevant information\r\n- **Command lined used (if not specified in steps to reproduce)**: main.py ...\r\n- **Operating system and version:** Windows, macOS, Linux \r\n- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5494/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5494/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5492","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5492/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5492/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5492/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5492","id":1167527925,"node_id":"I_kwDOCBuapc5Flw_1","number":5492,"title":"SAEHD training on GPU  run the pause command after start in Terminal","user":{"login":"Pips01","id":99753890,"node_id":"U_kgDOBfIfog","avatar_url":"https://avatars.githubusercontent.com/u/99753890?v=4","gravatar_id":"","url":"https://api.github.com/users/Pips01","html_url":"https://github.com/Pips01","followers_url":"https://api.github.com/users/Pips01/followers","following_url":"https://api.github.com/users/Pips01/following{/other_user}","gists_url":"https://api.github.com/users/Pips01/gists{/gist_id}","starred_url":"https://api.github.com/users/Pips01/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Pips01/subscriptions","organizations_url":"https://api.github.com/users/Pips01/orgs","repos_url":"https://api.github.com/users/Pips01/repos","events_url":"https://api.github.com/users/Pips01/events{/privacy}","received_events_url":"https://api.github.com/users/Pips01/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-03-13T09:31:14Z","updated_at":"2022-03-23T03:30:38Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hello,\r\n\r\nMy PC: Acer aspire 7, Core i 7 9th generation, nvidia geforce GTX 1050, Windows 10 home\r\n\r\nWhen I run SAEHD-training on GPU he run the pause command and say some thing like: \"Press any key to continue...\" after Start. On CPU work every thing fine!\r\nMy batch size is 4!\r\nSo my CMD is on German but look:\r\n![grafik](https://user-images.githubusercontent.com/99753890/158054791-f88b5eff-03ac-46ff-9f5f-143dfa55b93a.png)\r\n\r\n\"Drücken sie eine belibige Taste...\" mean \"Press any key to continue...\"\r\n\r\n\r\nTanks for your help😀!","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5492/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5492/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5490","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5490/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5490/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5490/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5490","id":1159533151,"node_id":"I_kwDOCBuapc5FHRJf","number":5490,"title":"Hello","user":{"login":"Creadec","id":28162240,"node_id":"MDQ6VXNlcjI4MTYyMjQw","avatar_url":"https://avatars.githubusercontent.com/u/28162240?v=4","gravatar_id":"","url":"https://api.github.com/users/Creadec","html_url":"https://github.com/Creadec","followers_url":"https://api.github.com/users/Creadec/followers","following_url":"https://api.github.com/users/Creadec/following{/other_user}","gists_url":"https://api.github.com/users/Creadec/gists{/gist_id}","starred_url":"https://api.github.com/users/Creadec/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Creadec/subscriptions","organizations_url":"https://api.github.com/users/Creadec/orgs","repos_url":"https://api.github.com/users/Creadec/repos","events_url":"https://api.github.com/users/Creadec/events{/privacy}","received_events_url":"https://api.github.com/users/Creadec/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-03-04T11:16:11Z","updated_at":"2022-03-13T09:40:15Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"@iperov Иван, добрый день!\r\n\r\nХотим познакомится на предмет сотрудничества. Если это возможно, свяжитесь со мной через creadec@gmail.com \r\n\r\nС уважением, Иван Суслин","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5490/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5490/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5489","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5489/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5489/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5489/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5489","id":1159485590,"node_id":"I_kwDOCBuapc5FHFiW","number":5489,"title":"Error when trying to utilise existing models/pre-trained models","user":{"login":"Loz13","id":46567610,"node_id":"MDQ6VXNlcjQ2NTY3NjEw","avatar_url":"https://avatars.githubusercontent.com/u/46567610?v=4","gravatar_id":"","url":"https://api.github.com/users/Loz13","html_url":"https://github.com/Loz13","followers_url":"https://api.github.com/users/Loz13/followers","following_url":"https://api.github.com/users/Loz13/following{/other_user}","gists_url":"https://api.github.com/users/Loz13/gists{/gist_id}","starred_url":"https://api.github.com/users/Loz13/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Loz13/subscriptions","organizations_url":"https://api.github.com/users/Loz13/orgs","repos_url":"https://api.github.com/users/Loz13/repos","events_url":"https://api.github.com/users/Loz13/events{/privacy}","received_events_url":"https://api.github.com/users/Loz13/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-03-04T10:24:15Z","updated_at":"2022-03-25T11:14:40Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"I've searched through the forums and numerous fixes for at least 6 hours without luck.... here's the issue\r\n\r\nI can successfully train a new SAEHD model, however, whenever I try to use existing models or pre-trained models, it says 2 root errors found. I have tried the following fixes but issue still pertains:\r\n\r\n- Used a range of other pre-trained or trained models including:\r\n         ->https://github.com/iperov/DeepFaceLab/releases/tag/DF.wf.288res.384.92.72.22\r\n         ->https://mrdeepfakes.com/forums/thread-sharing-dfl-2-0-saehd-models\r\n- Downloading fresh version of the 20.11.2021 RTX3000 series, I have a RTX3070 Ti\r\n- Turned on \"hardware-accelerated GPU scheduling\" in windows\r\n- made a change to line in \"$HOME/DeepFaceLab_Linux/DeepFaceLab/core/imagelib/warp.py\"\r\n   Original line:\r\n      random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)\r\n   Updated line that now allows me to train via SAEHD without issue:\r\n      random_transform_mat = cv2.getRotationMatrix2D((int(w // 2), int(w // 2)), rotation, scale)\r\n\r\nGreat thanks in advance and let me know if I missed any details....\r\n\r\n==================== Model Summary ====================\r\n==                                                   ==\r\n==            Model name: DF-UD448_SAEHD             ==\r\n==                                                   ==\r\n==     Current iteration: 248471                     ==\r\n==                                                   ==\r\n==------------------ Model Options ------------------==\r\n==                                                   ==\r\n==            resolution: 448                        ==\r\n==             face_type: wf                         ==\r\n==     models_opt_on_gpu: True                       ==\r\n==                 archi: df-ud                      ==\r\n==               ae_dims: 256                        ==\r\n==                e_dims: 64                         ==\r\n==                d_dims: 64                         ==\r\n==           d_mask_dims: 22                         ==\r\n==       masked_training: True                       ==\r\n==           uniform_yaw: True                       ==\r\n==            lr_dropout: n                          ==\r\n==           random_warp: True                       ==\r\n==             gan_power: 0.0                        ==\r\n==       true_face_power: 0.0                        ==\r\n==      face_style_power: 0.0                        ==\r\n==        bg_style_power: 0.0                        ==\r\n==               ct_mode: none                       ==\r\n==              clipgrad: False                      ==\r\n==              pretrain: False                      ==\r\n==       autobackup_hour: 0                          ==\r\n== write_preview_history: False                      ==\r\n==           target_iter: 0                          ==\r\n==           random_flip: False                      ==\r\n==            batch_size: 8                          ==\r\n==       eyes_mouth_prio: False                      ==\r\n==         blur_out_mask: False                      ==\r\n==             adabelief: True                       ==\r\n==      random_hsv_power: 0.0                        ==\r\n==       random_src_flip: False                      ==\r\n==       random_dst_flip: True                       ==\r\n==        gan_patch_size: 56                         ==\r\n==              gan_dims: 16                         ==\r\n==                                                   ==\r\n==------------------- Running On --------------------==\r\n==                                                   ==\r\n==          Device index: 0                          ==\r\n==                  Name: NVIDIA GeForce RTX 3070 Ti ==\r\n==                  VRAM: 5.34GB                     ==\r\n==                                                   ==\r\n=======================================================\r\n\r\n\r\nStarting. Press \"Enter\" to stop training and save model.\r\nError: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[1024,116,116] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[node Pad_7 (defined at C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py:87) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_5/concat/_465]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[1024,116,116] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[node Pad_7 (defined at C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py:87) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nErrors may have originated from an input operation.\r\nInput Source operations connected to node Pad_7:\r\n LeakyRelu_6 (defined at C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py:29)\r\n\r\nInput Source operations connected to node Pad_7:\r\n LeakyRelu_6 (defined at C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py:29)\r\n\r\nOriginal stack trace for 'Pad_7':\r\n  File \"threading.py\", line 884, in _bootstrap\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 58, in trainerThread\r\n    debug=debug)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 193, in __init__\r\n    self.on_initialize()\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 408, in on_initialize\r\n    gpu_dst_code     = self.inter(self.encoder(gpu_warped_dst))\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 119, in forward\r\n    x = self.down1(x)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 63, in forward\r\n    x = down(x)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 43, in forward\r\n    x = self.conv1(x)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\LayerBase.py\", line 14, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py\", line 87, in forward\r\n    x = tf.pad (x, padding, mode='CONSTANT')\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 206, in wrapper\r\n    return target(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\array_ops.py\", line 3528, in pad\r\n    result = gen_array_ops.pad(tensor, paddings, name=name)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\gen_array_ops.py\", line 6487, in pad\r\n    \"Pad\", input=input, paddings=paddings, name=name)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 750, in _apply_op_helper\r\n    attrs=attr_protos, op_def=op_def)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3569, in _create_op_internal\r\n    op_def=op_def)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2045, in __init__\r\n    self._traceback = tf_stack.extract_stack_for_node(self._c_op)\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1375, in _do_call\r\n    return fn(*args)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1360, in _run_fn\r\n    target_list, run_metadata)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1453, in _call_tf_sessionrun\r\n    run_metadata)\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[1024,116,116] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[{{node Pad_7}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_5/concat/_465]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[1024,116,116] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[{{node Pad_7}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 129, in trainerThread\r\n    iter, iter_time = model.train_one_iter()\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 474, in train_one_iter\r\n    losses = self.onTrainOneIter()\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 774, in onTrainOneIter\r\n    src_loss, dst_loss = self.src_dst_train (warped_src, target_src, target_srcm, target_srcm_em, warped_dst, target_dst, target_dstm, target_dstm_em)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 584, in src_dst_train\r\n    self.target_dstm_em:target_dstm_em,\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 968, in run\r\n    run_metadata_ptr)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1191, in _run\r\n    feed_dict_tensor, options, run_metadata)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1369, in _do_run\r\n    run_metadata)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1394, in _do_call\r\n    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[1024,116,116] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[node Pad_7 (defined at C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py:87) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n         [[concat_5/concat/_465]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[1024,116,116] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\r\n         [[node Pad_7 (defined at C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py:87) ]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nErrors may have originated from an input operation.\r\nInput Source operations connected to node Pad_7:\r\n LeakyRelu_6 (defined at C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py:29)\r\n\r\nInput Source operations connected to node Pad_7:\r\n LeakyRelu_6 (defined at C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py:29)\r\n\r\nOriginal stack trace for 'Pad_7':\r\n  File \"threading.py\", line 884, in _bootstrap\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 58, in trainerThread\r\n    debug=debug)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 193, in __init__\r\n    self.on_initialize()\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 408, in on_initialize\r\n    gpu_dst_code     = self.inter(self.encoder(gpu_warped_dst))\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 119, in forward\r\n    x = self.down1(x)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 63, in forward\r\n    x = down(x)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\models\\ModelBase.py\", line 117, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\archis\\DeepFakeArchi.py\", line 43, in forward\r\n    x = self.conv1(x)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\LayerBase.py\", line 14, in __call__\r\n    return self.forward(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\leras\\layers\\Conv2D.py\", line 87, in forward\r\n    x = tf.pad (x, padding, mode='CONSTANT')\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 206, in wrapper\r\n    return target(*args, **kwargs)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\array_ops.py\", line 3528, in pad\r\n    result = gen_array_ops.pad(tensor, paddings, name=name)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\gen_array_ops.py\", line 6487, in pad\r\n    \"Pad\", input=input, paddings=paddings, name=name)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 750, in _apply_op_helper\r\n    attrs=attr_protos, op_def=op_def)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3569, in _create_op_internal\r\n    op_def=op_def)\r\n  File \"C:\\Users\\Frank\\Desktop\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2045, in __init__\r\n    self._traceback = tf_stack.extract_stack_for_node(self._c_op)`\r\n","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5489/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5489/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5488","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5488/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5488/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5488/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5488","id":1153432703,"node_id":"I_kwDOCBuapc5Ev_x_","number":5488,"title":"Training (xseg/saehd) issue with windows 10 and AMD rx6900xt","user":{"login":"wiromare","id":16557836,"node_id":"MDQ6VXNlcjE2NTU3ODM2","avatar_url":"https://avatars.githubusercontent.com/u/16557836?v=4","gravatar_id":"","url":"https://api.github.com/users/wiromare","html_url":"https://github.com/wiromare","followers_url":"https://api.github.com/users/wiromare/followers","following_url":"https://api.github.com/users/wiromare/following{/other_user}","gists_url":"https://api.github.com/users/wiromare/gists{/gist_id}","starred_url":"https://api.github.com/users/wiromare/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/wiromare/subscriptions","organizations_url":"https://api.github.com/users/wiromare/orgs","repos_url":"https://api.github.com/users/wiromare/repos","events_url":"https://api.github.com/users/wiromare/events{/privacy}","received_events_url":"https://api.github.com/users/wiromare/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-02-27T22:52:34Z","updated_at":"2022-02-27T22:59:42Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Windows 10\r\nAMD rx6900xt with the latest driver\r\nDeepFaceLab_DirectX12_build_11_20_2021\r\n\r\nI have a strange behavior while training both xseg and saehd, it may happen that during the process the stats on the training windows stops to update, they are freezed, I can hear the fans go quiet, then I cannot update with 'p' in the preview window or save the iterations, it can remain so blocked even for 10 minutes and then resume the process without apparent problems or remain freezed forever so i have to close the windows and restart the process to the latest saved iterations, what happens? I have tried various batch sizes but the situation does not change\r\n\r\nanother strange things is that during the process the time stats increase from 1000ms up to even 2000ms after a couple of hours (when everythings goes fine with my first problem), is that normal?\r\n\r\nwith these situations seems impossible to leave deepfacelab to work alone without having to check that everything is ok\r\n\r\np.s.\r\n\r\nsince at moment amd with the most recent drivers seems do not support \"GPU Hardware Scheduling\" , is there a drop in performance without being able to enable that option? ","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5488/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5488/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5487","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5487/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5487/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5487/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5487","id":1153418142,"node_id":"I_kwDOCBuapc5Ev8Oe","number":5487,"title":"Getting weird things when training","user":{"login":"boerenhugo","id":67152268,"node_id":"MDQ6VXNlcjY3MTUyMjY4","avatar_url":"https://avatars.githubusercontent.com/u/67152268?v=4","gravatar_id":"","url":"https://api.github.com/users/boerenhugo","html_url":"https://github.com/boerenhugo","followers_url":"https://api.github.com/users/boerenhugo/followers","following_url":"https://api.github.com/users/boerenhugo/following{/other_user}","gists_url":"https://api.github.com/users/boerenhugo/gists{/gist_id}","starred_url":"https://api.github.com/users/boerenhugo/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/boerenhugo/subscriptions","organizations_url":"https://api.github.com/users/boerenhugo/orgs","repos_url":"https://api.github.com/users/boerenhugo/repos","events_url":"https://api.github.com/users/boerenhugo/events{/privacy}","received_events_url":"https://api.github.com/users/boerenhugo/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2022-02-27T22:03:21Z","updated_at":"2022-03-15T09:38:10Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hey could someone please help with this or is it a bug in the system because I am getting this when my training is done and I am getting this when I only have like 500 iterations... so does someone know the answer? (Directx12 with AMD rx480)\r\n![unknown (2)](https://user-images.githubusercontent.com/67152268/155901770-372cecd5-f1a3-4953-9d8a-9f5b214df964.png)","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5487/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5487/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5486","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5486/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5486/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5486/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5486","id":1153389409,"node_id":"I_kwDOCBuapc5Ev1Nh","number":5486,"title":"Solved for me: 2080 ti crashing on Train or Merge ","user":{"login":"samfisherirl","id":98753696,"node_id":"U_kgDOBeLcoA","avatar_url":"https://avatars.githubusercontent.com/u/98753696?v=4","gravatar_id":"","url":"https://api.github.com/users/samfisherirl","html_url":"https://github.com/samfisherirl","followers_url":"https://api.github.com/users/samfisherirl/followers","following_url":"https://api.github.com/users/samfisherirl/following{/other_user}","gists_url":"https://api.github.com/users/samfisherirl/gists{/gist_id}","starred_url":"https://api.github.com/users/samfisherirl/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/samfisherirl/subscriptions","organizations_url":"https://api.github.com/users/samfisherirl/orgs","repos_url":"https://api.github.com/users/samfisherirl/repos","events_url":"https://api.github.com/users/samfisherirl/events{/privacy}","received_events_url":"https://api.github.com/users/samfisherirl/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-02-27T20:34:30Z","updated_at":"2022-03-01T01:57:48Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS\r\nPOST ONLY ISSUES RELATED TO BUGS OR CODE\r\n\r\n## Expected behavior\r\n\r\nTaking 20 seconds of video, and transcribing another 20 second video with an individuals face. Training the AI. \r\n\r\n## Actual behavior\r\n\r\nCrashing upon attempting to train or merge, BSOD with \"DPC WATCHDOG VIOLATION\" Similar to about 1/4 of the posts listed below mine. \r\n\r\n## Steps to reproduce\r\n\r\nTaking two videos, successfully going through steps 1-5 without issue. Extracting faces, manually or automatically. If I attempted any steps towards train or merge, I was met with BSOD. Quick, or any other.\r\n\r\n## Other relevant information\r\n-2080 ti ROG STRIX Asus\r\n-i7 8700k 5ghz\r\n-32gb ram\r\n-Windows 10 fresh install 1 month\r\n\r\nAfter an hour of reading through the git and forums, I found the ability via underclocking my card and setting limits within the application. \r\n\r\nMy card was overclocked in MSI Afterburner, even without the overclock the system would crash. CPU was reset to standard clock, that didn't help.  Running  only CPU wasnt something I was interested in testing due to time constraints. \r\n\r\n![image](https://user-images.githubusercontent.com/98753696/155898797-348b26c7-8725-42da-bdd2-1dfaa25d29cf.png)\r\n\r\nUpon underclocking my memory, core, and power, I was able to maintain a stable outcome. \r\n\r\nI also kept taskers at 8/12? I assume when they ask that its relating either to cores or VRAM. \r\n\r\nI can only assume the application Deepface isn't accounting for my limited VRAM and is using all of it. That seems to be most likely. If thats right, patches should limit the ceiling  VRAM, whatever is maxing out system on the gpu. That, or have heavy warnings for the upper bound. ","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5486/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5486/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5485","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5485/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5485/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5485/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5485","id":1153318167,"node_id":"I_kwDOCBuapc5Evj0X","number":5485,"title":"Error: No training data provided.","user":{"login":"BrianStark","id":100529226,"node_id":"U_kgDOBf30Sg","avatar_url":"https://avatars.githubusercontent.com/u/100529226?v=4","gravatar_id":"","url":"https://api.github.com/users/BrianStark","html_url":"https://github.com/BrianStark","followers_url":"https://api.github.com/users/BrianStark/followers","following_url":"https://api.github.com/users/BrianStark/following{/other_user}","gists_url":"https://api.github.com/users/BrianStark/gists{/gist_id}","starred_url":"https://api.github.com/users/BrianStark/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/BrianStark/subscriptions","organizations_url":"https://api.github.com/users/BrianStark/orgs","repos_url":"https://api.github.com/users/BrianStark/repos","events_url":"https://api.github.com/users/BrianStark/events{/privacy}","received_events_url":"https://api.github.com/users/BrianStark/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2022-02-27T16:50:01Z","updated_at":"2022-03-12T00:18:04Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Good afternoon,\r\n\r\nI tried to run the program but I keep getting the same error continuously,\r\nI reinstalled my Windows 11 to see if that was the issue, and even tried it with Windows 8 and 10.\r\nBut I keep getting this error, it would be really nice if there is a solution for it.\r\n\r\ncould it be that my system is not good??\r\nI have a computer with the parts:\r\n\r\nCPU:          AMD Ryzen Threadripper 2990WX 32-Core Processor\r\nRAM:         128 GB\r\nGPU:          NVIDIA GeForce RTX 2080 Ti\r\nSSD:          GIGABYTE GP-AG42TB (2TB)\r\n\r\n\r\n\r\n(GPU i'm going to upgrade to 2x NVIDIA GeForce RTX 3090)\r\n\r\n\r\nThanks in advance for the help.\r\n\r\n\r\n\r\nRunning trainer.\r\n\r\n[new] No saved models found. Enter a name of a new model : new_model\r\nnew_model\r\n\r\nModel first run.\r\n\r\nChoose one or several GPU idxs (separated by comma).\r\n\r\n[CPU] : CPU\r\n  [0] : NVIDIA GeForce RTX 2080 Ti\r\n\r\n[0] Which GPU indexes to choose? :\r\n0\r\n\r\n[0] Autobackup every N hour ( 0..24 ?:help ) :\r\n0\r\n[n] Write preview history ( y/n ?:help ) :\r\nn\r\n[0] Target iteration :\r\n0\r\n[n] Flip SRC faces randomly ( y/n ?:help ) :\r\nn\r\n[y] Flip DST faces randomly ( y/n ?:help ) :\r\ny\r\n[8] Batch_size ( ?:help ) :\r\n8\r\n[128] Resolution ( 64-640 ?:help ) :\r\n128\r\n[f] Face type ( h/mf/f/wf/head ?:help ) :\r\nf\r\n[liae-ud] AE architecture ( ?:help ) :\r\nliae-ud\r\n[256] AutoEncoder dimensions ( 32-1024 ?:help ) :\r\n256\r\n[64] Encoder dimensions ( 16-256 ?:help ) :\r\n64\r\n[64] Decoder dimensions ( 16-256 ?:help ) :\r\n64\r\n[22] Decoder mask dimensions ( 16-256 ?:help ) :\r\n22\r\n[n] Eyes and mouth priority ( y/n ?:help ) :\r\nn\r\n[n] Uniform yaw distribution of samples ( y/n ?:help ) :\r\nn\r\n[n] Blur out mask ( y/n ?:help ) :\r\nn\r\n[y] Place models and optimizer on GPU ( y/n ?:help ) :\r\ny\r\n[y] Use AdaBelief optimizer? ( y/n ?:help ) :\r\ny\r\n[n] Use learning rate dropout ( n/y/cpu ?:help ) :\r\nn\r\n[y] Enable random warp of samples ( y/n ?:help ) :\r\ny\r\n[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) :\r\n0.0\r\n[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :\r\n0.0\r\n[0.0] Face style power ( 0.0..100.0 ?:help ) :\r\n0.0\r\n[0.0] Background style power ( 0.0..100.0 ?:help ) :\r\n0.0\r\n[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :\r\nnone\r\n[n] Enable gradient clipping ( y/n ?:help ) : y\r\n[n] Enable pretraining mode ( y/n ?:help ) : y\r\nInitializing models: 100%|############################################################| 5/5 [00:03<00:00,  1.52it/s]\r\nLoading samples: 0it [00:00, ?it/s]\r\nError: No training data provided.\r\nTraceback (most recent call last):\r\n  File \"D:\\Ai FaceFake 2\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 58, in trainerThread\r\n    debug=debug)\r\n  File \"D:\\Ai FaceFake 2\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 193, in __init__\r\n    self.on_initialize()\r\n  File \"D:\\Ai FaceFake 2\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 684, in on_initialize\r\n    generators_count=src_generators_count ),\r\n  File \"D:\\Ai FaceFake 2\\_internal\\DeepFaceLab\\samplelib\\SampleGeneratorFace.py\", line 48, in __init__\r\n    raise ValueError('No training data provided.')\r\nValueError: No training data provided.","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5485/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5485/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5484","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5484/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5484/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5484/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5484","id":1150751454,"node_id":"I_kwDOCBuapc5ElxLe","number":5484,"title":"Is SAEhd Broken for gtx 1080 drivers? 2 Root errors out the box. nothing has been changed.","user":{"login":"HDNinecloudz","id":100440463,"node_id":"U_kgDOBfyZjw","avatar_url":"https://avatars.githubusercontent.com/u/100440463?v=4","gravatar_id":"","url":"https://api.github.com/users/HDNinecloudz","html_url":"https://github.com/HDNinecloudz","followers_url":"https://api.github.com/users/HDNinecloudz/followers","following_url":"https://api.github.com/users/HDNinecloudz/following{/other_user}","gists_url":"https://api.github.com/users/HDNinecloudz/gists{/gist_id}","starred_url":"https://api.github.com/users/HDNinecloudz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/HDNinecloudz/subscriptions","organizations_url":"https://api.github.com/users/HDNinecloudz/orgs","repos_url":"https://api.github.com/users/HDNinecloudz/repos","events_url":"https://api.github.com/users/HDNinecloudz/events{/privacy}","received_events_url":"https://api.github.com/users/HDNinecloudz/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2022-02-25T18:52:08Z","updated_at":"2022-02-25T19:41:44Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Running SAEhd on CPU gives this error: internal compiler error, abnormal program termination.\r\n\r\nRunning SAEhd on GPU gives me this error\r\n\r\n================== Model Summary ===================\r\n==                                                ==\r\n==            Model name: new_SAEHD               ==\r\n==                                                ==\r\n==     Current iteration: 1000000                 ==\r\n==                                                ==\r\n==---------------- Model Options -----------------==\r\n==                                                ==\r\n==            resolution: 288                     ==\r\n==             face_type: wf                      ==\r\n==     models_opt_on_gpu: True                    ==\r\n==                 archi: df                      ==\r\n==               ae_dims: 384                     ==\r\n==                e_dims: 92                      ==\r\n==                d_dims: 72                      ==\r\n==           d_mask_dims: 22                      ==\r\n==       masked_training: True                    ==\r\n==            lr_dropout: n                       ==\r\n==           random_warp: False                   ==\r\n==             gan_power: 0.0                     ==\r\n==       true_face_power: 0.0                     ==\r\n==      face_style_power: 0.0                     ==\r\n==        bg_style_power: 0.0                     ==\r\n==               ct_mode: none                    ==\r\n==              clipgrad: False                   ==\r\n==              pretrain: True                    ==\r\n==       autobackup_hour: 0                       ==\r\n== write_preview_history: False                   ==\r\n==           target_iter: 1000000000              ==\r\n==           random_flip: True                    ==\r\n==            batch_size: 4                       ==\r\n==       eyes_mouth_prio: True                    ==\r\n==           uniform_yaw: True                    ==\r\n==         blur_out_mask: False                   ==\r\n==             adabelief: True                    ==\r\n==      random_hsv_power: 0.0                     ==\r\n==       random_src_flip: False                   ==\r\n==       random_dst_flip: True                    ==\r\n==        gan_patch_size: 36                      ==\r\n==              gan_dims: 16                      ==\r\n==                                                ==\r\n==------------------ Running On ------------------==\r\n==                                                ==\r\n==          Device index: 0                       ==\r\n==                  Name: NVIDIA GeForce GTX 1080 ==\r\n==                  VRAM: 6.78GB                  ==\r\n==                                                ==\r\n====================================================\r\nStarting. Target iteration: 1000000000. Press \"Enter\" to stop training and save model.\r\nError: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[4,576,72,72] and type float on /job:localhost/replica:0/task:0/device:DML:0 by allocator DmlAllocator\r\n         [[{{node ArithmeticOptimizer/AddOpsRewrite_Leaf_1_add_34}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n         [[concat_1/concat/_417]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[4,576,72,72] and type float on /job:localhost/replica:0/task:0/device:DML:0 by allocator DmlAllocator\r\n         [[{{node ArithmeticOptimizer/AddOpsRewrite_Leaf_1_add_34}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\nTraceback (most recent call last):\r\n  File \"C:\\Games\\dpl\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow_core\\python\\client\\session.py\", line 1365, in _do_call\r\n    return fn(*args)\r\n  File \"C:\\Games\\dpl\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow_core\\python\\client\\session.py\", line 1350, in _run_fn\r\n    target_list, run_metadata)\r\n  File \"C:\\Games\\dpl\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow_core\\python\\client\\session.py\", line 1443, in _call_tf_sessionrun\r\n    run_metadata)\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[4,576,72,72] and type float on /job:localhost/replica:0/task:0/device:DML:0 by allocator DmlAllocator\r\n         [[{{node ArithmeticOptimizer/AddOpsRewrite_Leaf_1_add_34}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n         [[concat_1/concat/_417]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[4,576,72,72] and type float on /job:localhost/replica:0/task:0/device:DML:0 by allocator DmlAllocator\r\n         [[{{node ArithmeticOptimizer/AddOpsRewrite_Leaf_1_add_34}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Games\\dpl\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 129, in trainerThread\r\n    iter, iter_time = model.train_one_iter()\r\n  File \"C:\\Games\\dpl\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 474, in train_one_iter\r\n    losses = self.onTrainOneIter()\r\n  File \"C:\\Games\\dpl\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 774, in onTrainOneIter\r\n    src_loss, dst_loss = self.src_dst_train (warped_src, target_src, target_srcm, target_srcm_em, warped_dst, target_dst, target_dstm, target_dstm_em)\r\n  File \"C:\\Games\\dpl\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 584, in src_dst_train\r\n    self.target_dstm_em:target_dstm_em,\r\n  File \"C:\\Games\\dpl\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow_core\\python\\client\\session.py\", line 956, in run\r\n    run_metadata_ptr)\r\n  File \"C:\\Games\\dpl\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow_core\\python\\client\\session.py\", line 1180, in _run\r\n    feed_dict_tensor, options, run_metadata)\r\n  File \"C:\\Games\\dpl\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow_core\\python\\client\\session.py\", line 1359, in _do_run\r\n    run_metadata)\r\n  File \"C:\\Games\\dpl\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow_core\\python\\client\\session.py\", line 1384, in _do_call\r\n    raise type(e)(node_def, op, message)\r\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.\r\n  (0) Resource exhausted: OOM when allocating tensor with shape[4,576,72,72] and type float on /job:localhost/replica:0/task:0/device:DML:0 by allocator DmlAllocator\r\n         [[{{node ArithmeticOptimizer/AddOpsRewrite_Leaf_1_add_34}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n         [[concat_1/concat/_417]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n  (1) Resource exhausted: OOM when allocating tensor with shape[4,576,72,72] and type float on /job:localhost/replica:0/task:0/device:DML:0 by allocator DmlAllocator\r\n         [[{{node ArithmeticOptimizer/AddOpsRewrite_Leaf_1_add_34}}]]\r\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\r\n\r\n0 successful operations.\r\n0 derived errors ignored.\r\n\r\nI dont know what to do with all this. i cant find the Run options the Hints are telling me to change. so im assuming the current build is destroyed? or is it the pretrained faces? cause honestly i tried deleting the facepak and the whole program wont work without it. pls help","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5484/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5484/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5483","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5483/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5483/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5483/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5483","id":1145636491,"node_id":"I_kwDOCBuapc5ESQaL","number":5483,"title":"WINDOWS 11 - Xseg - data_dst mask - edit  ->  qt.qpa.plugin: Could not find the Qt platform plugin \"windows\" in .....","user":{"login":"4M0NK","id":100129985,"node_id":"U_kgDOBffcwQ","avatar_url":"https://avatars.githubusercontent.com/u/100129985?v=4","gravatar_id":"","url":"https://api.github.com/users/4M0NK","html_url":"https://github.com/4M0NK","followers_url":"https://api.github.com/users/4M0NK/followers","following_url":"https://api.github.com/users/4M0NK/following{/other_user}","gists_url":"https://api.github.com/users/4M0NK/gists{/gist_id}","starred_url":"https://api.github.com/users/4M0NK/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/4M0NK/subscriptions","organizations_url":"https://api.github.com/users/4M0NK/orgs","repos_url":"https://api.github.com/users/4M0NK/repos","events_url":"https://api.github.com/users/4M0NK/events{/privacy}","received_events_url":"https://api.github.com/users/4M0NK/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-02-21T10:55:19Z","updated_at":"2022-03-27T13:13:27Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Running XSeg editor.\r\nqt.qpa.plugin: Could not find the Qt platform plugin \"windows\" in \"C:\\Users\\IMA ISLAND BOY\\OneDrive\\PoŔÝtaŔ\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\Lib\\site-packages\\PyQt5\\Qt\\plugins\"\r\nThis application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.\r\n\r\nI did reinstall the program but the problem persist","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5483/reactions","total_count":1,"+1":1,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5483/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5482","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5482/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5482/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5482/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5482","id":1144980855,"node_id":"I_kwDOCBuapc5EPwV3","number":5482,"title":"no cuDNN stream anymore....","user":{"login":"doc1977","id":100070391,"node_id":"U_kgDOBfbz9w","avatar_url":"https://avatars.githubusercontent.com/u/100070391?v=4","gravatar_id":"","url":"https://api.github.com/users/doc1977","html_url":"https://github.com/doc1977","followers_url":"https://api.github.com/users/doc1977/followers","following_url":"https://api.github.com/users/doc1977/following{/other_user}","gists_url":"https://api.github.com/users/doc1977/gists{/gist_id}","starred_url":"https://api.github.com/users/doc1977/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/doc1977/subscriptions","organizations_url":"https://api.github.com/users/doc1977/orgs","repos_url":"https://api.github.com/users/doc1977/repos","events_url":"https://api.github.com/users/doc1977/events{/privacy}","received_events_url":"https://api.github.com/users/doc1977/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-02-20T10:34:17Z","updated_at":"2022-02-20T10:34:17Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"## Expected behavior\r\n\r\nTo work normally as it did the last months\r\n\r\n## Actual behavior\r\n\r\nEvery step in the DFL workflow that uses cuDNN produces same error message: \r\n\r\nF tensorflow/stream_executor/cuda/cuda_dnn.cc:194] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.\r\n\r\n## Steps to reproduce\r\n\r\nsimply retry to run it :-P\r\n\r\n## Other relevant information\r\nOccured first after NVIDIA Driver update to most latest version. Tried a Rollback with deinstalling Drivers via DDU application and reinstalling old version but problem is persisting.\r\n\r\nWindows 10\r\nNVIDIA GTX 1660 Super\r\nDeepFaceLab_NVIDIA_up_to_RTX2080Ti_build_11_20_2021\r\n\r\nACTUAL Driver/Version configuration:\r\n+-----------------------------------------------------------------------------+\r\n| NVIDIA-SMI 511.79       Driver Version: 511.79       CUDA Version: 11.6     |\r\n|-------------------------------+----------------------+----------------------+\r\n| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |\r\n| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\r\n|                               |                      |               MIG M. |\r\n|===============================+======================+======================|\r\n|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |\r\n|  0%   51C    P8    20W / 125W |    506MiB /  6144MiB |      0%      Default |\r\n|                               |                      |                  N/A |\r\n+-------------------------------+----------------------+----------------------+\r\n","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5482/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5482/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5481","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5481/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5481/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5481/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5481","id":1144025143,"node_id":"I_kwDOCBuapc5EMHA3","number":5481,"title":"Train Quick96 won't use NVIDIA GeForce GTX 465 GPU","user":{"login":"MontyMole98","id":99610944,"node_id":"U_kgDOBe_xQA","avatar_url":"https://avatars.githubusercontent.com/u/99610944?v=4","gravatar_id":"","url":"https://api.github.com/users/MontyMole98","html_url":"https://github.com/MontyMole98","followers_url":"https://api.github.com/users/MontyMole98/followers","following_url":"https://api.github.com/users/MontyMole98/following{/other_user}","gists_url":"https://api.github.com/users/MontyMole98/gists{/gist_id}","starred_url":"https://api.github.com/users/MontyMole98/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/MontyMole98/subscriptions","organizations_url":"https://api.github.com/users/MontyMole98/orgs","repos_url":"https://api.github.com/users/MontyMole98/repos","events_url":"https://api.github.com/users/MontyMole98/events{/privacy}","received_events_url":"https://api.github.com/users/MontyMole98/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2022-02-19T00:33:06Z","updated_at":"2022-02-24T22:10:32Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"I am trying to run Train Quick96 with my NVIDIA GeForce GTX 465 GPU, but it keeps running on CPU. I have a newer PC with a CPU, which is running the training process around 5-6 times faster than the older one that I want to run using GPU. Still, I am determined to use the GPU on the older one. I will post any pictures if needed. Thanks in advance!","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5481/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5481/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5480","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5480/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5480/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5480/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5480","id":1142992242,"node_id":"I_kwDOCBuapc5EIK1y","number":5480,"title":"training problem","user":{"login":"liewcm","id":99966865,"node_id":"U_kgDOBfVfkQ","avatar_url":"https://avatars.githubusercontent.com/u/99966865?v=4","gravatar_id":"","url":"https://api.github.com/users/liewcm","html_url":"https://github.com/liewcm","followers_url":"https://api.github.com/users/liewcm/followers","following_url":"https://api.github.com/users/liewcm/following{/other_user}","gists_url":"https://api.github.com/users/liewcm/gists{/gist_id}","starred_url":"https://api.github.com/users/liewcm/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/liewcm/subscriptions","organizations_url":"https://api.github.com/users/liewcm/orgs","repos_url":"https://api.github.com/users/liewcm/repos","events_url":"https://api.github.com/users/liewcm/events{/privacy}","received_events_url":"https://api.github.com/users/liewcm/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-02-18T12:43:40Z","updated_at":"2022-02-18T12:43:40Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Running trainer.\r\n\r\nChoose one of saved models, or enter a name to create a new model.\r\n[r] : rename\r\n[d] : delete\r\n\r\n[0] : new - latest\r\n :\r\n0\r\nLoading new_Quick96 model...\r\n\r\nChoose one or several GPU idxs (separated by comma).\r\n\r\n[CPU] : CPU\r\n  [0] : NVIDIA GeForce RTX 3060\r\n\r\n[0] Which GPU indexes to choose? :\r\n0\r\n\r\nInitializing models: 100%|###############################################################| 5/5 [00:01<00:00,  4.34it/s]\r\nLoading samples: 100%|###################################################################| 1/1 [00:00<00:00, 11.00it/s]\r\nLoading samples: 100%|###################################################################| 1/1 [00:00<00:00,  9.64it/s]\r\n================ Model Summary =================\r\n==                                            ==\r\n==        Model name: new_Quick96             ==\r\n==                                            ==\r\n== Current iteration: 2153                    ==\r\n==                                            ==\r\n==-------------- Model Options ---------------==\r\n==                                            ==\r\n==        batch_size: 4                       ==\r\n==                                            ==\r\n==---------------- Running On ----------------==\r\n==                                            ==\r\n==      Device index: 0                       ==\r\n==              Name: NVIDIA GeForce RTX 3060 ==\r\n==              VRAM: 10.55GB                 ==\r\n==                                            ==\r\n================================================\r\nStarting. Press \"Enter\" to stop training and save model.\r\nPress any key to continue . . .\r\n","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5480/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5480/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5479","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5479/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5479/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5479/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5479","id":1141978734,"node_id":"I_kwDOCBuapc5EETZu","number":5479,"title":"feature request : 3d face overlay with xyz axes control to change angle during manyual extraction","user":{"login":"2blackbar","id":33694664,"node_id":"MDQ6VXNlcjMzNjk0NjY0","avatar_url":"https://avatars.githubusercontent.com/u/33694664?v=4","gravatar_id":"","url":"https://api.github.com/users/2blackbar","html_url":"https://github.com/2blackbar","followers_url":"https://api.github.com/users/2blackbar/followers","following_url":"https://api.github.com/users/2blackbar/following{/other_user}","gists_url":"https://api.github.com/users/2blackbar/gists{/gist_id}","starred_url":"https://api.github.com/users/2blackbar/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/2blackbar/subscriptions","organizations_url":"https://api.github.com/users/2blackbar/orgs","repos_url":"https://api.github.com/users/2blackbar/repos","events_url":"https://api.github.com/users/2blackbar/events{/privacy}","received_events_url":"https://api.github.com/users/2blackbar/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-02-17T22:21:27Z","updated_at":"2022-02-17T22:21:27Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"I hope this will come one day, some ultra low or high angles are impossible to extrack when you just see bottom of the nose and chin or top of the head and nose\r\n","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5479/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5479/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5478","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5478/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5478/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5478/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5478","id":1139045449,"node_id":"I_kwDOCBuapc5D5HRJ","number":5478,"title":"Deep face lab SAEHD OMM error...?","user":{"login":"Pips01","id":99753890,"node_id":"U_kgDOBfIfog","avatar_url":"https://avatars.githubusercontent.com/u/99753890?v=4","gravatar_id":"","url":"https://api.github.com/users/Pips01","html_url":"https://github.com/Pips01","followers_url":"https://api.github.com/users/Pips01/followers","following_url":"https://api.github.com/users/Pips01/following{/other_user}","gists_url":"https://api.github.com/users/Pips01/gists{/gist_id}","starred_url":"https://api.github.com/users/Pips01/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Pips01/subscriptions","organizations_url":"https://api.github.com/users/Pips01/orgs","repos_url":"https://api.github.com/users/Pips01/repos","events_url":"https://api.github.com/users/Pips01/events{/privacy}","received_events_url":"https://api.github.com/users/Pips01/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2022-02-15T18:14:13Z","updated_at":"2022-03-13T13:25:28Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hey guys,\r\nI have an acer ASPIRE 7 laptop, a CORE i7 9th Gen, a GEFORCE GTX 1050, 8 Gigabite RAM and Windows 10 Home. I use DFL 2.0 and \"DeepFaceLab_NVIDIA_up_to_RTX2080Ti\"- Version\r\n\r\nI have started the training with almost all the sand values and an my GPU, but I get an error:\r\n\r\nMy values\r\n\r\n![grafik](https://user-images.githubusercontent.com/99753890/154122222-9bdc913f-4ac7-40b7-8036-02c48e478f3c.png)\r\n\r\nThe Error:\r\n![grafik](https://user-images.githubusercontent.com/99753890/154122433-0efb0891-c78a-41ed-ae39-5c4853a29912.png)\r\n![grafik](https://user-images.githubusercontent.com/99753890/154122498-62fe1601-e8fc-4797-9f16-b68d50b11a56.png)\r\n \r\nOn CPU I got the same Error.\r\nA Quick model work fine.\r\n\r\nThanks for your help!","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5478/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5478/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5477","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5477/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5477/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5477/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5477","id":1134739570,"node_id":"I_kwDOCBuapc5DosBy","number":5477,"title":"How about old reliable mask painting ?","user":{"login":"2blackbar","id":33694664,"node_id":"MDQ6VXNlcjMzNjk0NjY0","avatar_url":"https://avatars.githubusercontent.com/u/33694664?v=4","gravatar_id":"","url":"https://api.github.com/users/2blackbar","html_url":"https://github.com/2blackbar","followers_url":"https://api.github.com/users/2blackbar/followers","following_url":"https://api.github.com/users/2blackbar/following{/other_user}","gists_url":"https://api.github.com/users/2blackbar/gists{/gist_id}","starred_url":"https://api.github.com/users/2blackbar/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/2blackbar/subscriptions","organizations_url":"https://api.github.com/users/2blackbar/orgs","repos_url":"https://api.github.com/users/2blackbar/repos","events_url":"https://api.github.com/users/2blackbar/events{/privacy}","received_events_url":"https://api.github.com/users/2blackbar/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-02-12T22:48:00Z","updated_at":"2022-02-12T22:48:24Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Masking is by far most irritating part of the process, the new generic auto mode is fine but it would be even better if masks would be saved as png images , then we would be able to see these images overlaid on our frames and paint over masks to add missing areas /remove errors that were included like obstructions.\r\nThis would be best worfklow for this, cause right now generic masking exists \"out there\" and we cant really do anything with it, so let us to  save it to pngs and then allow us to paint over it . It would be future proof until maybe something comes in the future.\r\nCurrent manual vs automatic workflow is PITA cause they exclude one another.","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5477/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5477/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5474","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5474/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5474/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5474/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5474","id":1132987352,"node_id":"I_kwDOCBuapc5DiAPY","number":5474,"title":"67251773","user":{"login":"notname956","id":99505992,"node_id":"U_kgDOBe5XSA","avatar_url":"https://avatars.githubusercontent.com/u/99505992?v=4","gravatar_id":"","url":"https://api.github.com/users/notname956","html_url":"https://github.com/notname956","followers_url":"https://api.github.com/users/notname956/followers","following_url":"https://api.github.com/users/notname956/following{/other_user}","gists_url":"https://api.github.com/users/notname956/gists{/gist_id}","starred_url":"https://api.github.com/users/notname956/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/notname956/subscriptions","organizations_url":"https://api.github.com/users/notname956/orgs","repos_url":"https://api.github.com/users/notname956/repos","events_url":"https://api.github.com/users/notname956/events{/privacy}","received_events_url":"https://api.github.com/users/notname956/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-02-11T19:11:50Z","updated_at":"2022-02-11T19:11:50Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":null,"reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5474/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5474/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5473","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5473/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5473/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5473/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5473","id":1127992178,"node_id":"I_kwDOCBuapc5DO8ty","number":5473,"title":"train saehd.bat stuck after pressing key to continue","user":{"login":"pjflippy123","id":99305748,"node_id":"U_kgDOBetJFA","avatar_url":"https://avatars.githubusercontent.com/u/99305748?v=4","gravatar_id":"","url":"https://api.github.com/users/pjflippy123","html_url":"https://github.com/pjflippy123","followers_url":"https://api.github.com/users/pjflippy123/followers","following_url":"https://api.github.com/users/pjflippy123/following{/other_user}","gists_url":"https://api.github.com/users/pjflippy123/gists{/gist_id}","starred_url":"https://api.github.com/users/pjflippy123/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pjflippy123/subscriptions","organizations_url":"https://api.github.com/users/pjflippy123/orgs","repos_url":"https://api.github.com/users/pjflippy123/repos","events_url":"https://api.github.com/users/pjflippy123/events{/privacy}","received_events_url":"https://api.github.com/users/pjflippy123/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":8,"created_at":"2022-02-09T03:03:42Z","updated_at":"2022-03-26T01:17:01Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Running trainer.\r\n\r\n[new] No saved models found. Enter a name of a new model :\r\nnew\r\n\r\nModel first run.\r\n\r\nChoose one or several GPU idxs (separated by comma).\r\n\r\n[CPU] : CPU\r\n  [0] : NVIDIA GeForce RTX 2070\r\n\r\n[0] Which GPU indexes to choose? :\r\n0\r\n\r\n[1] Autobackup every N hour ( 0..24 ?:help ) :\r\n1\r\n[n] Write preview history ( y/n ?:help ) :\r\nn\r\n[0] Target iteration :\r\n0\r\n[y] Flip SRC faces randomly ( y/n ?:help ) :\r\ny\r\n[y] Flip DST faces randomly ( y/n ?:help ) :\r\ny\r\n[4] Batch_size ( ?:help ) :\r\n4\r\n[96] Resolution ( 64-640 ?:help ) :\r\n96\r\n[wf] Face type ( h/mf/f/wf/head ?:help ) :\r\nwf\r\n[df] AE architecture ( ?:help ) :\r\ndf\r\n[256] AutoEncoder dimensions ( 32-1024 ?:help ) :\r\n256\r\n[64] Encoder dimensions ( 16-256 ?:help ) :\r\n64\r\n[64] Decoder dimensions ( 16-256 ?:help ) :\r\n64\r\n[22] Decoder mask dimensions ( 16-256 ?:help ) :\r\n22\r\n[y] Masked training ( y/n ?:help ) :\r\ny\r\n[n] Eyes and mouth priority ( y/n ?:help ) :\r\nn\r\n[n] Uniform yaw distribution of samples ( y/n ?:help ) :\r\nn\r\n[n] Blur out mask ( y/n ?:help ) :\r\nn\r\n[y] Place models and optimizer on GPU ( y/n ?:help ) :\r\ny\r\n[n] Use AdaBelief optimizer? ( y/n ?:help ) :\r\nn\r\n[n] Use learning rate dropout ( n/y/cpu ?:help ) :\r\nn\r\n[y] Enable random warp of samples ( y/n ?:help ) :\r\ny\r\n[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) :\r\n0.0\r\n[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :\r\n0.0\r\n[0.0] 'True face' power. ( 0.0000 .. 1.0 ?:help ) :\r\n0.0\r\n[0.0] Face style power ( 0.0..100.0 ?:help ) :\r\n0.0\r\n[0.0] Background style power ( 0.0..100.0 ?:help ) :\r\n0.0\r\n[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :\r\nnone\r\n[n] Enable gradient clipping ( y/n ?:help ) :\r\nn\r\n[n] Enable pretraining mode ( y/n ?:help ) :\r\nn\r\nInitializing models: 100%|###############################################################| 5/5 [00:01<00:00,  2.71it/s]\r\nLoading samples: 100%|############################################################| 2256/2256 [00:04<00:00, 503.05it/s]\r\nLoading samples: 100%|##############################################################| 816/816 [00:01<00:00, 461.83it/s]\r\nPress any key to continue . . .\r\n\r\n\r\ngets stuck here \r\n\r\n![image](https://user-images.githubusercontent.com/99305748/153113928-411bb5b9-a9a7-4e5f-9dde-524ac9b9e8e9.png)\r\n\r\nuses the same amount of ram for 8 hours i had it open but never once opened the trainer or got past this stage\r\n\r\nusing i7 with a rtx 2070 16 gb of ram\r\n","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5473/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5473/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5472","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5472/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5472/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5472/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5472","id":1125769347,"node_id":"I_kwDOCBuapc5DGeCD","number":5472,"title":"Exception while trying to train SAEHD","user":{"login":"dflguru","id":99176396,"node_id":"U_kgDOBelPzA","avatar_url":"https://avatars.githubusercontent.com/u/99176396?v=4","gravatar_id":"","url":"https://api.github.com/users/dflguru","html_url":"https://github.com/dflguru","followers_url":"https://api.github.com/users/dflguru/followers","following_url":"https://api.github.com/users/dflguru/following{/other_user}","gists_url":"https://api.github.com/users/dflguru/gists{/gist_id}","starred_url":"https://api.github.com/users/dflguru/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dflguru/subscriptions","organizations_url":"https://api.github.com/users/dflguru/orgs","repos_url":"https://api.github.com/users/dflguru/repos","events_url":"https://api.github.com/users/dflguru/events{/privacy}","received_events_url":"https://api.github.com/users/dflguru/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-02-07T10:06:25Z","updated_at":"2022-02-07T10:06:25Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"OS: Windows 11 x64\r\nDFL Version: DeepFaceLab_NVIDIA_RTX3000_series_build_11_20_2021\r\nGPU: nVidia GeForce RTX 3090 FE\r\nCPU: AMD Ryzen Threadripper 3960x\r\nRAM: 32G\r\n----\r\n\r\nAfter extracting faces of src and dst, I tried to train using SAEHD. I have RTX 2080 Super and RTX 3090 plugged on to my motherboard, but I use RTX 3090 only. Let me paste the trace below to refer the configs I have provided and the exception;\r\n\r\n```\r\nRunning trainer.\r\n\r\n[new] No saved models found. Enter a name of a new model : test_saehd\r\ntest_saehd\r\n\r\nModel first run.\r\n\r\nChoose one or several GPU idxs (separated by comma).\r\n\r\n[CPU] : CPU\r\n  [0] : NVIDIA GeForce RTX 3090\r\n  [1] : NVIDIA GeForce RTX 2080 SUPER\r\n\r\n[0] Which GPU indexes to choose? : 0\r\n0\r\n\r\n[1] Autobackup every N hour ( 0..24 ?:help ) : 1\r\n1\r\n[n] Write preview history ( y/n ?:help ) :\r\nn\r\n[0] Target iteration :\r\n0\r\n[n] Flip SRC faces randomly ( y/n ?:help ) :\r\nn\r\n[y] Flip DST faces randomly ( y/n ?:help ) :\r\ny\r\n[8] Batch_size ( ?:help ) :\r\n8\r\n[128] Resolution ( 64-640 ?:help ) :\r\n128\r\n[f] Face type ( h/mf/f/wf/head ?:help ) :\r\nf\r\n[liae-ud] AE architecture ( ?:help ) :\r\nliae-ud\r\n[256] AutoEncoder dimensions ( 32-1024 ?:help ) :\r\n256\r\n[64] Encoder dimensions ( 16-256 ?:help ) :\r\n64\r\n[64] Decoder dimensions ( 16-256 ?:help ) :\r\n64\r\n[22] Decoder mask dimensions ( 16-256 ?:help ) :\r\n22\r\n[n] Eyes and mouth priority ( y/n ?:help ) :\r\nn\r\n[n] Uniform yaw distribution of samples ( y/n ?:help ) :\r\nn\r\n[n] Blur out mask ( y/n ?:help ) :\r\nn\r\n[y] Place models and optimizer on GPU ( y/n ?:help ) :\r\ny\r\n[y] Use AdaBelief optimizer? ( y/n ?:help ) :\r\ny\r\n[n] Use learning rate dropout ( n/y/cpu ?:help ) :\r\nn\r\n[y] Enable random warp of samples ( y/n ?:help ) :\r\ny\r\n[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) :\r\n0.0\r\n[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :\r\n0.0\r\n[0.0] Face style power ( 0.0..100.0 ?:help ) :\r\n0.0\r\n[0.0] Background style power ( 0.0..100.0 ?:help ) :\r\n0.0\r\n[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :\r\nnone\r\n[n] Enable gradient clipping ( y/n ?:help ) :\r\nn\r\n[n] Enable pretraining mode ( y/n ?:help ) :\r\nn\r\nInitializing models: 100%|###############################################################| 5/5 [00:01<00:00,  3.42it/s]\r\nLoading samples: 100%|############################################################| 4270/4270 [00:08<00:00, 496.97it/s]\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"multiprocessing\\spawn.py\", line 105, in spawn_main\r\nException in thread Thread-25:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n  File \"multiprocessing\\spawn.py\", line 115, in _main\r\n\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\samplelib\\__init__.py\", line 1, in <module>\r\n    from .Sample import Sample\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\samplelib\\Sample.py\", line 7, in <module>\r\n    from core.cv2ex import *\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\cv2ex.py\", line 5, in <module>\r\n    from core import imagelib\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\imagelib\\__init__.py\", line 5, in <module>\r\n    from .text import get_text_image, get_draw_text_lines\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\imagelib\\text.py\", line 3, in <module>\r\n    from PIL import Image, ImageDraw, ImageFont\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap_external>\", line 674, in exec_module\r\n  File \"<frozen importlib._bootstrap_external>\", line 764, in get_code\r\n  File \"<frozen importlib._bootstrap_external>\", line 833, in get_data\r\nMemoryError\r\n```\r\n\r\nSomebody please tell me why this is happening and how to fix this?\r\n\r\nthe entire error trace is like below;\r\n\r\n```\r\nRunning trainer.\r\n\r\n[new] No saved models found. Enter a name of a new model : test_saehd\r\ntest_saehd\r\n\r\nModel first run.\r\n\r\nChoose one or several GPU idxs (separated by comma).\r\n\r\n[CPU] : CPU\r\n  [0] : NVIDIA GeForce RTX 3090\r\n  [1] : NVIDIA GeForce RTX 2080 SUPER\r\n\r\n[0] Which GPU indexes to choose? : 0\r\n0\r\n\r\n[1] Autobackup every N hour ( 0..24 ?:help ) : 1\r\n1\r\n[n] Write preview history ( y/n ?:help ) :\r\nn\r\n[0] Target iteration :\r\n0\r\n[n] Flip SRC faces randomly ( y/n ?:help ) :\r\nn\r\n[y] Flip DST faces randomly ( y/n ?:help ) :\r\ny\r\n[8] Batch_size ( ?:help ) :\r\n8\r\n[128] Resolution ( 64-640 ?:help ) :\r\n128\r\n[f] Face type ( h/mf/f/wf/head ?:help ) :\r\nf\r\n[liae-ud] AE architecture ( ?:help ) :\r\nliae-ud\r\n[256] AutoEncoder dimensions ( 32-1024 ?:help ) :\r\n256\r\n[64] Encoder dimensions ( 16-256 ?:help ) :\r\n64\r\n[64] Decoder dimensions ( 16-256 ?:help ) :\r\n64\r\n[22] Decoder mask dimensions ( 16-256 ?:help ) :\r\n22\r\n[n] Eyes and mouth priority ( y/n ?:help ) :\r\nn\r\n[n] Uniform yaw distribution of samples ( y/n ?:help ) :\r\nn\r\n[n] Blur out mask ( y/n ?:help ) :\r\nn\r\n[y] Place models and optimizer on GPU ( y/n ?:help ) :\r\ny\r\n[y] Use AdaBelief optimizer? ( y/n ?:help ) :\r\ny\r\n[n] Use learning rate dropout ( n/y/cpu ?:help ) :\r\nn\r\n[y] Enable random warp of samples ( y/n ?:help ) :\r\ny\r\n[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) :\r\n0.0\r\n[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :\r\n0.0\r\n[0.0] Face style power ( 0.0..100.0 ?:help ) :\r\n0.0\r\n[0.0] Background style power ( 0.0..100.0 ?:help ) :\r\n0.0\r\n[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :\r\nnone\r\n[n] Enable gradient clipping ( y/n ?:help ) :\r\nn\r\n[n] Enable pretraining mode ( y/n ?:help ) :\r\nn\r\nInitializing models: 100%|###############################################################| 5/5 [00:01<00:00,  3.42it/s]\r\nLoading samples: 100%|############################################################| 4270/4270 [00:08<00:00, 496.97it/s]\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"multiprocessing\\spawn.py\", line 105, in spawn_main\r\nException in thread Thread-25:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n  File \"multiprocessing\\spawn.py\", line 115, in _main\r\n\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\samplelib\\__init__.py\", line 1, in <module>\r\n    from .Sample import Sample\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\samplelib\\Sample.py\", line 7, in <module>\r\n    from core.cv2ex import *\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\cv2ex.py\", line 5, in <module>\r\n    from core import imagelib\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\imagelib\\__init__.py\", line 5, in <module>\r\n    from .text import get_text_image, get_draw_text_lines\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\imagelib\\text.py\", line 3, in <module>\r\n    from PIL import Image, ImageDraw, ImageFont\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap_external>\", line 674, in exec_module\r\n  File \"<frozen importlib._bootstrap_external>\", line 764, in get_code\r\n  File \"<frozen importlib._bootstrap_external>\", line 833, in get_data\r\nMemoryError\r\nException in thread Thread-22:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-13:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-10:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-18:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-21:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-27:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-14:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-15:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-12:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-16:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-23:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-6:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-24:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-7:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-26:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-20:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-9:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-5:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-19:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-8:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-17:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-11:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n\r\nException in thread Thread-4:\r\nTraceback (most recent call last):\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 11, in launch_thread\r\n    generator._start()\r\n  File \"C:\\Users\\User\\Documents\\DF\\DFLab\\DeepFaceLab_NVIDIA_RTX3000_series\\_internal\\DeepFaceLab\\core\\joblib\\SubprocessGenerator.py\", line 43, in _start\r\n    p.start()\r\n  File \"multiprocessing\\process.py\", line 105, in start\r\n  File \"multiprocessing\\context.py\", line 223, in _Popen\r\n  File \"multiprocessing\\context.py\", line 322, in _Popen\r\n  File \"multiprocessing\\popen_spawn_win32.py\", line 65, in __init__\r\n  File \"multiprocessing\\reduction.py\", line 60, in dump\r\nBrokenPipeError: [Errno 32] Broken pipe\r\n```\r\n","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5472/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5472/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5471","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5471/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5471/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5471/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5471","id":1124031887,"node_id":"I_kwDOCBuapc5C_12P","number":5471,"title":"Input images dst checked after loading faces during at 7) merge SAEHD.bat","user":{"login":"thedeepface","id":99017328,"node_id":"U_kgDOBebicA","avatar_url":"https://avatars.githubusercontent.com/u/99017328?v=4","gravatar_id":"","url":"https://api.github.com/users/thedeepface","html_url":"https://github.com/thedeepface","followers_url":"https://api.github.com/users/thedeepface/followers","following_url":"https://api.github.com/users/thedeepface/following{/other_user}","gists_url":"https://api.github.com/users/thedeepface/gists{/gist_id}","starred_url":"https://api.github.com/users/thedeepface/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/thedeepface/subscriptions","organizations_url":"https://api.github.com/users/thedeepface/orgs","repos_url":"https://api.github.com/users/thedeepface/repos","events_url":"https://api.github.com/users/thedeepface/events{/privacy}","received_events_url":"https://api.github.com/users/thedeepface/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-02-04T10:17:57Z","updated_at":"2022-02-04T10:17:57Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hello \r\n\r\nI noticed that the extracted images from data_dst.mp4 are checked after the model and src/dst faces are loaded.\r\n\r\nThis means in larger projects of 60.000 images, it takes quite some time to find out that you are missing your data_dst extracted images.\r\n\r\nThis check should be done first before proceeding to load model and src/dst faces to avoid this waste of time.\r\n\r\nNow you could say just extract the data_dst.mp4 beforehand, but there are some cases that you need to delete them partially, or fully, \r\n\r\nSo its better to do the precheck of the data_dst.mp4 extracted images as first step to avoid timeloss. Or give the user the chance to extract it(mention that files are not there, please extract and press on y to continue). That would be good","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5471/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5471/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5470","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5470/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5470/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5470/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5470","id":1122738296,"node_id":"I_kwDOCBuapc5C66B4","number":5470,"title":"?","user":{"login":"scholism","id":98940954,"node_id":"U_kgDOBeW4Gg","avatar_url":"https://avatars.githubusercontent.com/u/98940954?v=4","gravatar_id":"","url":"https://api.github.com/users/scholism","html_url":"https://github.com/scholism","followers_url":"https://api.github.com/users/scholism/followers","following_url":"https://api.github.com/users/scholism/following{/other_user}","gists_url":"https://api.github.com/users/scholism/gists{/gist_id}","starred_url":"https://api.github.com/users/scholism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/scholism/subscriptions","organizations_url":"https://api.github.com/users/scholism/orgs","repos_url":"https://api.github.com/users/scholism/repos","events_url":"https://api.github.com/users/scholism/events{/privacy}","received_events_url":"https://api.github.com/users/scholism/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-02-03T07:22:16Z","updated_at":"2022-03-13T10:26:23Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS\r\nPOST ONLY ISSUES RELATED TO BUGS OR CODE\r\n\r\n## Expected behavior\r\n\r\n*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*\r\n\r\n## Actual behavior\r\n\r\n*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*\r\n\r\n## Steps to reproduce\r\n\r\n*Describe, in some detail, the steps you tried that resulted in the behavior described above.*\r\n\r\n## Other relevant information\r\n- **Command lined used (if not specified in steps to reproduce)**: main.py ...\r\n- **Operating system and version:** Windows, macOS, Linux \r\n- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binar\r\n\r\nF tensorflow/core/kernels/dml_ops_common.cc:184] HRESULT failed with 0x887a0005: dml_device->CompileOperator(op.Get(), execution_flags, IID_PPV_ARGS(&compiled_op))","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5470/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5470/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5469","repository_url":"https://api.github.com/repos/iperov/DeepFaceLab","labels_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5469/labels{/name}","comments_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5469/comments","events_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5469/events","html_url":"https://github.com/iperov/DeepFaceLab/issues/5469","id":1122616429,"node_id":"I_kwDOCBuapc5C6cRt","number":5469,"title":"I can't run seahd on the gpu! it only runs on the cpu","user":{"login":"alan9455","id":98932376,"node_id":"U_kgDOBeWWmA","avatar_url":"https://avatars.githubusercontent.com/u/98932376?v=4","gravatar_id":"","url":"https://api.github.com/users/alan9455","html_url":"https://github.com/alan9455","followers_url":"https://api.github.com/users/alan9455/followers","following_url":"https://api.github.com/users/alan9455/following{/other_user}","gists_url":"https://api.github.com/users/alan9455/gists{/gist_id}","starred_url":"https://api.github.com/users/alan9455/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alan9455/subscriptions","organizations_url":"https://api.github.com/users/alan9455/orgs","repos_url":"https://api.github.com/users/alan9455/repos","events_url":"https://api.github.com/users/alan9455/events{/privacy}","received_events_url":"https://api.github.com/users/alan9455/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2022-02-03T03:34:42Z","updated_at":"2022-02-15T21:50:24Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Initializing models: 80%|######################################## ######4 | 4/5 [00:28<00:07, 7.18s/it]\r\nError: OOM when allocating tensor of shape [3,3,512,2048] and type float\r\n         [[node src_dst_opt/vs_inter_B/upscale1/conv1/weight_0/Initializer/Const (defined at D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py:38) ]]\r\n\r\nCaused by op 'src_dst_opt/vs_inter_B/upscale1/conv1/weight_0/Initializer/Const', defined at:\r\n  File \"threading.py\", line 884, in _bootstrap\r\n  File \"threading.py\", line 916, in _bootstrap_inner\r\n  File \"threading.py\", line 864, in run\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\DeepFaceLab\\mainscripts\\Trainer.py\", line 58, in trainerThread\r\n    debug=debug)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\DeepFaceLab\\models\\ModelBase.py\", line 193, in __init__\r\n    self.on_initialize()\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\DeepFaceLab\\models\\Model_SAEHD\\Model.py\", line 341, in on_initialize\r\n    self.src_dst_opt.initialize_variables (self.src_dst_saveable_weights, vars_on_cpu=optimizer_vars_on_cpu, lr_dropout_on_cpu=self.options['lr_dropout']=='cpu')\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py\", line 38, in initialize_variables\r\n    vs = { v.name : tf.get_variable ( f'vs_{v.name}'.replace(':','_'), v.shape, dtype=v.dtype, initializer=tf.initializers.constant( 0.0), trainable=False) for v in trainable_weights }\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\DeepFaceLab\\core\\leras\\optimizers\\AdaBelief.py\", line 38, in <dictcomp>\r\n    vs = { v.name : tf.get_variable ( f'vs_{v.name}'.replace(':','_'), v.shape, dtype=v.dtype, initializer=tf.initializers.constant( 0.0), trainable=False) for v in trainable_weights }\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 1479, in get_variable\r\n    aggregation=aggregation)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 1220, in get_variable\r\n    aggregation=aggregation)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 547, in get_variable\r\n    aggregation=aggregation)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 499, in _true_getter\r\n    aggregation=aggregation)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 911, in _get_single_variable\r\n    aggregation=aggregation)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 213, in __call__\r\n    return cls._variable_v1_call(*args, **kwargs)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 176, in _variable_v1_call\r\n    aggregation=aggregation)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 155, in <lambda>\r\n    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 2495, in default_variable_creator\r\n    expected_shape=expected_shape, import_scope=import_scope)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 217, in __call__\r\n    return super(VariableMetaclass, cls).__call__(*args, **kwargs)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 1395, in __init__\r\n    constraint=constraint)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variables.py\", line 1503, in _init_from_args\r\n    initial_value(), name=\"initial_value\", dtype=dtype)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\variable_scope.py\", line 883, in <lambda>\r\n    shape.as_list(), dtype=dtype, partition_info=partition_info)\r\n  File \"D:\\deepfake\\DeepFaceLab\\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\\_internal\\python-3.6.8\\lib\\site-packages\\tensorflow\\python\\ops\\init_ops.py\", line 230, in __call__\r\n    self.value, dtype=dtype, shape=shape\r\n\r\n\r\n\r\n\r\n============ Model Summary ============\r\n==                                   ==\r\n==            Model name: new_SAEHD  ==\r\n==                                   ==\r\n==     Current iteration: 564        ==\r\n==                                   ==\r\n==---------- Model Options ----------==\r\n==                                   ==\r\n==            resolution: 320        ==\r\n==             face_type: f          ==\r\n==     models_opt_on_gpu: True       ==\r\n==                 archi: liae-ud    ==\r\n==               ae_dims: 256        ==\r\n==                e_dims: 64         ==\r\n==                d_dims: 64         ==\r\n==           d_mask_dims: 22         ==\r\n==       masked_training: True       ==\r\n==       eyes_mouth_prio: False      ==\r\n==           uniform_yaw: False      ==\r\n==         blur_out_mask: False      ==\r\n==             adabelief: True       ==\r\n==            lr_dropout: n          ==\r\n==           random_warp: True       ==\r\n==      random_hsv_power: 0.0        ==\r\n==       true_face_power: 0.0        ==\r\n==      face_style_power: 0.0        ==\r\n==        bg_style_power: 0.0        ==\r\n==               ct_mode: none       ==\r\n==              clipgrad: False      ==\r\n==              pretrain: False      ==\r\n==       autobackup_hour: 0          ==\r\n== write_preview_history: False      ==\r\n==           target_iter: 3000000000 ==\r\n==       random_src_flip: False      ==\r\n==       random_dst_flip: True       ==\r\n==            batch_size: 4          ==\r\n==             gan_power: 0.0        ==\r\n==        gan_patch_size: 40         ==\r\n==              gan_dims: 16         ==\r\n==                                   ==\r\n==----------- Running On ------------==\r\n==                                   ==\r\n==          Using device: CPU        ==\r\n==                                   ==\r\n=======================================\r\n","reactions":{"url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5469/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/iperov/DeepFaceLab/issues/5469/timeline","performed_via_github_app":null}]