[{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46588","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46588/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46588/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46588/events","html_url":"https://github.com/pandas-dev/pandas/issues/46588","id":1188743032,"node_id":"I_kwDOAA0YD85G2sd4","number":46588,"title":"BUG: `Series.map` is ignoring the `na_action` keyword","user":{"login":"shortorian","id":13423221,"node_id":"MDQ6VXNlcjEzNDIzMjIx","avatar_url":"https://avatars.githubusercontent.com/u/13423221?v=4","gravatar_id":"","url":"https://api.github.com/users/shortorian","html_url":"https://github.com/shortorian","followers_url":"https://api.github.com/users/shortorian/followers","following_url":"https://api.github.com/users/shortorian/following{/other_user}","gists_url":"https://api.github.com/users/shortorian/gists{/gist_id}","starred_url":"https://api.github.com/users/shortorian/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/shortorian/subscriptions","organizations_url":"https://api.github.com/users/shortorian/orgs","repos_url":"https://api.github.com/users/shortorian/repos","events_url":"https://api.github.com/users/shortorian/events{/privacy}","received_events_url":"https://api.github.com/users/shortorian/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-31T20:49:24Z","updated_at":"2022-03-31T20:49:24Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\na = pd.Series([pd.NA, 1, 1, pd.NA])\r\na.map({1:2, pd.NA:3}, na_action=True)\n```\n\n\n### Issue Description\n\nThis code should throw an error because `na_action` is invalid, but instead I've gotten a Jupyter notebook, ipython in Powershell, and an online interpreter to generate the following output\r\n```\r\n0    3\r\n1    2\r\n2    2\r\n3    3\r\ndtype: int64\r\n```\r\nI get the same output for `na_action='ignore'` and `na_action=None`\n\n### Expected Behavior\n\n`ValueError: na_action must either be 'ignore' or None, True was passed`\n\n### Installed Versions\n\n<details>\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.9.12.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.22000\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 141 Stepping 1, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.22.3\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 22.0.4\r\nsetuptools       : 58.1.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 7.30.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : 1.4.28\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46588/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46588/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46587","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46587/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46587/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46587/events","html_url":"https://github.com/pandas-dev/pandas/issues/46587","id":1188663977,"node_id":"I_kwDOAA0YD85G2ZKp","number":46587,"title":"API/DES: Non-Nanosecond Tracker","user":{"login":"jbrockmendel","id":8078968,"node_id":"MDQ6VXNlcjgwNzg5Njg=","avatar_url":"https://avatars.githubusercontent.com/u/8078968?v=4","gravatar_id":"","url":"https://api.github.com/users/jbrockmendel","html_url":"https://github.com/jbrockmendel","followers_url":"https://api.github.com/users/jbrockmendel/followers","following_url":"https://api.github.com/users/jbrockmendel/following{/other_user}","gists_url":"https://api.github.com/users/jbrockmendel/gists{/gist_id}","starred_url":"https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jbrockmendel/subscriptions","organizations_url":"https://api.github.com/users/jbrockmendel/orgs","repos_url":"https://api.github.com/users/jbrockmendel/repos","events_url":"https://api.github.com/users/jbrockmendel/events{/privacy}","received_events_url":"https://api.github.com/users/jbrockmendel/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-31T20:08:40Z","updated_at":"2022-03-31T20:08:55Z","closed_at":null,"author_association":"MEMBER","active_lock_reason":null,"body":"Support for non-nanosecond timedelta64, datetime64, and datetime64tz is coming along.  The next big planned steps are to get the Timedelta and Timestamp scalars to support non-nano resolutions.  There are a few design options that I'd like to get input on cc @pandas-dev/pandas-core \r\n\r\nI'm doing Timedelta first mostly because that is more conducive to doing as a scoped PR with dedicated testing.  Current plan is to make a dedicated constructor like Timedelta._from_value_and_reso (so i can write tests) that can can be removed once we decide on the public behavior.  Which brings us to the questions:\r\n\r\n- Do we add a reso-like keyword to the constructors?  Or use/respect \"unit\"?\r\n- With non-nano np.timedelta64 objects that don't overflow when cast to nano, do we still cast?  e.g. does `np.datetime64(4, \"s\") become ns or stay s?\r\n- Similar with pytimedelta.  `pd.Timedelta(timedelta(days=106752))` currently raises, in the future will presumably come back with a 'us' reso.  So what about currently non-raising cases like `pd.Timedelta(timedelta(days=106751))`?  Does it stay ns or become us?\r\n \r\nOther\r\n1) What happens to (class attributes) (Timestamp|Timedelta)(min|max|resolution)?\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46587/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46587/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46586","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46586/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46586/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46586/events","html_url":"https://github.com/pandas-dev/pandas/pull/46586","id":1188094553,"node_id":"PR_kwDOAA0YD841ZjxX","number":46586,"title":"Ran sphinx-lint","user":{"login":"matilda-me","id":102734365,"node_id":"U_kgDOBh-aHQ","avatar_url":"https://avatars.githubusercontent.com/u/102734365?v=4","gravatar_id":"","url":"https://api.github.com/users/matilda-me","html_url":"https://github.com/matilda-me","followers_url":"https://api.github.com/users/matilda-me/followers","following_url":"https://api.github.com/users/matilda-me/following{/other_user}","gists_url":"https://api.github.com/users/matilda-me/gists{/gist_id}","starred_url":"https://api.github.com/users/matilda-me/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/matilda-me/subscriptions","organizations_url":"https://api.github.com/users/matilda-me/orgs","repos_url":"https://api.github.com/users/matilda-me/repos","events_url":"https://api.github.com/users/matilda-me/events{/privacy}","received_events_url":"https://api.github.com/users/matilda-me/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-03-31T13:37:58Z","updated_at":"2022-03-31T14:38:00Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/46586","html_url":"https://github.com/pandas-dev/pandas/pull/46586","diff_url":"https://github.com/pandas-dev/pandas/pull/46586.diff","patch_url":"https://github.com/pandas-dev/pandas/pull/46586.patch","merged_at":null},"body":"Found a few issues on the doc with [sphinx-lint](https://github.com/sphinx-contrib/sphinx-lint).\r\n\r\nFixed them.","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46586/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46586/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46584","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46584/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46584/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46584/events","html_url":"https://github.com/pandas-dev/pandas/issues/46584","id":1188009622,"node_id":"I_kwDOAA0YD85Gz5aW","number":46584,"title":"BUG: groupby with nans always places nans last","user":{"login":"rhshadrach","id":45562402,"node_id":"MDQ6VXNlcjQ1NTYyNDAy","avatar_url":"https://avatars.githubusercontent.com/u/45562402?v=4","gravatar_id":"","url":"https://api.github.com/users/rhshadrach","html_url":"https://github.com/rhshadrach","followers_url":"https://api.github.com/users/rhshadrach/followers","following_url":"https://api.github.com/users/rhshadrach/following{/other_user}","gists_url":"https://api.github.com/users/rhshadrach/gists{/gist_id}","starred_url":"https://api.github.com/users/rhshadrach/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rhshadrach/subscriptions","organizations_url":"https://api.github.com/users/rhshadrach/orgs","repos_url":"https://api.github.com/users/rhshadrach/repos","events_url":"https://api.github.com/users/rhshadrach/events{/privacy}","received_events_url":"https://api.github.com/users/rhshadrach/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":233160,"node_id":"MDU6TGFiZWwyMzMxNjA=","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Groupby","name":"Groupby","color":"729FCF","default":false,"description":null},{"id":2822342,"node_id":"MDU6TGFiZWwyODIyMzQy","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data","name":"Missing-data","color":"d7e102","default":false,"description":"np.nan, pd.NaT, pd.NA, dropna, isnull, interpolate"},{"id":57296398,"node_id":"MDU6TGFiZWw1NzI5NjM5OA==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Algos","name":"Algos","color":"eb6420","default":false,"description":"Non-arithmetic algos: value_counts, factorize, sorting, isin, clip, shift, diff"},{"id":697792067,"node_id":"MDU6TGFiZWw2OTc3OTIwNjc=","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Apply","name":"Apply","color":"fbca04","default":false,"description":"Apply, Aggregate, Transform"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pandas-dev/pandas/milestones/92","html_url":"https://github.com/pandas-dev/pandas/milestone/92","labels_url":"https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels","id":7530006,"node_id":"MI_kwDOAA0YD84AcuYW","number":92,"title":"1.5","description":"","creator":{"login":"jreback","id":953992,"node_id":"MDQ6VXNlcjk1Mzk5Mg==","avatar_url":"https://avatars.githubusercontent.com/u/953992?v=4","gravatar_id":"","url":"https://api.github.com/users/jreback","html_url":"https://github.com/jreback","followers_url":"https://api.github.com/users/jreback/followers","following_url":"https://api.github.com/users/jreback/following{/other_user}","gists_url":"https://api.github.com/users/jreback/gists{/gist_id}","starred_url":"https://api.github.com/users/jreback/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jreback/subscriptions","organizations_url":"https://api.github.com/users/jreback/orgs","repos_url":"https://api.github.com/users/jreback/repos","events_url":"https://api.github.com/users/jreback/events{/privacy}","received_events_url":"https://api.github.com/users/jreback/received_events","type":"User","site_admin":false},"open_issues":53,"closed_issues":600,"state":"open","created_at":"2021-12-31T21:51:13Z","updated_at":"2022-03-31T17:59:23Z","due_on":"2022-06-30T07:00:00Z","closed_at":null},"comments":0,"created_at":"2022-03-31T12:31:51Z","updated_at":"2022-03-31T12:31:58Z","closed_at":null,"author_association":"MEMBER","active_lock_reason":null,"body":"Marking as milestone 1.5 because this issue was introduced by #45953. While the output of the transform op below was also incorrect prior to this PR, we are reporting this kind of op as being fixed in the whatsnew.\r\n\r\nWhen specifying `sort=False` and `dropna=False` in groupby, any null groupers are moved to the end, even when `sort=False`:\r\n\r\n```\r\ndf = pd.DataFrame({'a': [1, 3, np.nan, 1, 2], 'b': [3, 4, 5, 6, 7]})\r\nprint(df.groupby('a', sort=False, dropna=False).grouper.result_index)\r\nprint(df.groupby('a', sort=True, dropna=False).grouper.result_index)\r\nprint(df.groupby('a', sort=False, dropna=False).sum())\r\n```\r\n\r\ngives\r\n\r\n```\r\nFloat64Index([1.0, 3.0, 2.0, nan], dtype='float64', name='a')\r\nFloat64Index([1.0, 2.0, 3.0, nan], dtype='float64', name='a')\r\n     b\r\na     \r\n1.0  9\r\n3.0  4\r\n2.0  7\r\nNaN  5\r\n```\r\n\r\nThis is because nan is always given the largest code from factorize:\r\n\r\n```\r\nprint(df.groupby('a', sort=False, dropna=False).codes)\r\n# np.nan's code is 3, even though it is the third group encountered and so should be code 2.\r\n[array([0, 1, 3, 0, 2])]\r\n```\r\n\r\nWhile only a minor issue for aggregations, transform depends on the code being properly ordered.\r\n\r\n```\r\nprint(df.groupby('a', sort=False, dropna=False).transform(lambda x: x))\r\n# Should be 3, 4, 5, 6, 7\r\n   b\r\n0  3\r\n1  4\r\n2  7\r\n3  6\r\n4  5\r\n```","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46584/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46584/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46583","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46583/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46583/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46583/events","html_url":"https://github.com/pandas-dev/pandas/issues/46583","id":1187941203,"node_id":"I_kwDOAA0YD85GzotT","number":46583,"title":"change the index in DataFrame.to_csv to False as default?","user":{"login":"KirderfEman","id":79636327,"node_id":"MDQ6VXNlcjc5NjM2MzI3","avatar_url":"https://avatars.githubusercontent.com/u/79636327?v=4","gravatar_id":"","url":"https://api.github.com/users/KirderfEman","html_url":"https://github.com/KirderfEman","followers_url":"https://api.github.com/users/KirderfEman/followers","following_url":"https://api.github.com/users/KirderfEman/following{/other_user}","gists_url":"https://api.github.com/users/KirderfEman/gists{/gist_id}","starred_url":"https://api.github.com/users/KirderfEman/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/KirderfEman/subscriptions","organizations_url":"https://api.github.com/users/KirderfEman/orgs","repos_url":"https://api.github.com/users/KirderfEman/repos","events_url":"https://api.github.com/users/KirderfEman/events{/privacy}","received_events_url":"https://api.github.com/users/KirderfEman/received_events","type":"User","site_admin":false},"labels":[{"id":76812,"node_id":"MDU6TGFiZWw3NjgxMg==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement","name":"Enhancement","color":"4E9A06","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-31T11:32:44Z","updated_at":"2022-03-31T11:32:44Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Maybe it’s time in some future release change the index in DataFrame.to_csv to False as default? Just a feeling that many change it manually from True to False every time using it...\r\n\r\nThanks for a 10/10 product!","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46583/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46583/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46582","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46582/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46582/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46582/events","html_url":"https://github.com/pandas-dev/pandas/issues/46582","id":1187859377,"node_id":"I_kwDOAA0YD85GzUux","number":46582,"title":"BUG: pandas cannot recognize date objects as datetime like values","user":{"login":"dcsaba89","id":54766615,"node_id":"MDQ6VXNlcjU0NzY2NjE1","avatar_url":"https://avatars.githubusercontent.com/u/54766615?v=4","gravatar_id":"","url":"https://api.github.com/users/dcsaba89","html_url":"https://github.com/dcsaba89","followers_url":"https://api.github.com/users/dcsaba89/followers","following_url":"https://api.github.com/users/dcsaba89/following{/other_user}","gists_url":"https://api.github.com/users/dcsaba89/gists{/gist_id}","starred_url":"https://api.github.com/users/dcsaba89/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dcsaba89/subscriptions","organizations_url":"https://api.github.com/users/dcsaba89/orgs","repos_url":"https://api.github.com/users/dcsaba89/repos","events_url":"https://api.github.com/users/dcsaba89/events{/privacy}","received_events_url":"https://api.github.com/users/dcsaba89/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-31T10:20:43Z","updated_at":"2022-03-31T10:20:43Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport datetime as dt\r\nimport pandas as pd\r\n\r\nd1 = dt.datetime(2020, 10, 10)\r\nyear1 = d1.year  # This works, year1 == 2020\r\n\r\nd2 = dt.date(2020, 10, 10)\r\nyear2 = d2.year  # This works, year2 == 2020\r\n\r\ndf = pd.DataFrame({'DATE_STR': ['2020-10-10']})\r\ndf['DATETIME'] = pd.to_datetime(df['DATE_STR'])\r\ndf['DATE'] = df['DATETIME'].dt.date\r\n\r\n\r\nprint(df.to_string(index=False))\r\n\r\nyearA = df['DATETIME'].dt.year # This works\r\nyearB = df['DATE'].dt.year  # AttributeError: Can only use .dt accessor with datetimelike values. Did you mean: 'at'?\n```\n\n\n### Issue Description\n\nPandas cannot recognize datetime.date(...) objects as datetime like values.\r\n\r\npandas.Series.dt.year, pandas.Series.dt.month, pandas.Series.dt.day, etc ... does not work with dt.date(...) objects.\n\n### Expected Behavior\n\ndf['DATETIME'].dt.year and df['DATE'].dt.year must be identical if df['DATETIME'] and df['DATE'] contains the same dates as datetime and date objects respectively.\r\n\r\nIn general, all pd.Series.dt methods like day, month, year, etc that replicates datetime methods for pd.Series should return the same output as the underlying datetime methd.\r\n\r\nFor example if dt.datetime(2020, 10, 10).month and dt.date(2020, 10, 10).month both return 10, then pd.Series([dt.datetime(2020, 10, 10)]).dt.month and pd.Series([dt.date(2020, 10, 10)]).dt.month should be identical and should return the same value ( = 10) as the underlying datetime methods.\n\n### Installed Versions\n\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5\r\npython           : 3.9.7.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.22000\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\n\r\npandas           : 1.3.4\r\nnumpy            : 1.20.3\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 58.0.4\r\nCython           : 0.29.24\r\npytest           : 6.2.4\r\nhypothesis       : None\r\nsphinx           : 4.2.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 3.0.1\r\nlxml.etree       : 4.6.3\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.3\r\nIPython          : 7.29.0\r\npandas_datareader: None\r\nbs4              : 4.10.0\r\nbottleneck       : 1.3.2\r\nfsspec           : 2021.10.1\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : 3.4.3\r\nnumexpr          : 2.7.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.7.1\r\nsqlalchemy       : 1.4.22\r\ntables           : 3.6.1\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 2.0.1\r\nxlwt             : 1.3.0\r\nnumba            : 0.54.1","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46582/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46582/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46581","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46581/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46581/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46581/events","html_url":"https://github.com/pandas-dev/pandas/issues/46581","id":1187766119,"node_id":"I_kwDOAA0YD85Gy99n","number":46581,"title":"BUG: Possible bug with `Series.agg()`","user":{"login":"kwhkim","id":4476168,"node_id":"MDQ6VXNlcjQ0NzYxNjg=","avatar_url":"https://avatars.githubusercontent.com/u/4476168?v=4","gravatar_id":"","url":"https://api.github.com/users/kwhkim","html_url":"https://github.com/kwhkim","followers_url":"https://api.github.com/users/kwhkim/followers","following_url":"https://api.github.com/users/kwhkim/following{/other_user}","gists_url":"https://api.github.com/users/kwhkim/gists{/gist_id}","starred_url":"https://api.github.com/users/kwhkim/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kwhkim/subscriptions","organizations_url":"https://api.github.com/users/kwhkim/orgs","repos_url":"https://api.github.com/users/kwhkim/repos","events_url":"https://api.github.com/users/kwhkim/events{/privacy}","received_events_url":"https://api.github.com/users/kwhkim/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-31T09:18:02Z","updated_at":"2022-03-31T15:51:50Z","closed_at":null,"author_association":"CONTRIBUTOR","active_lock_reason":null,"body":"### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\nI must admit there were similar complaints before, here I present my analysis and solution. (ex. [API: Signature of UDF methods](https://github.com/pandas-dev/pandas/issues/40112), [Higher Order Methods API](https://github.com/pandas-dev/pandas/issues/41112))\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\nimport numpy as np\r\ndat = pd.DataFrame({'color':['A', 'A', 'E', 'E', 'J'],\r\n                    'carat':[0.23, 0.21, 0.23, 0.29, 0.31],\r\n                    'x':[3.95, 3.89, 4.05, 4.20, 4.34]},\r\n                  index = [1,2,3,4,5])\r\n\r\ndat['carat'].agg(np.mean)\r\n## 0.254\r\ndat['carat'].agg(np.mean, axis=0)\r\n## 0.254\r\ndat['carat'].agg('mean')\r\n## 0.254\r\ndat['carat'].agg(lambda x: np.mean(x))\r\n## 1    0.23\r\n## 2    0.21\r\n## 3    0.23\r\n## 4    0.29\r\n## 5    0.31\r\n## Name: carat, dtype: float64\r\ndat['carat'].agg(lambda x, axis: np.mean(x, axis=axis), axis=0)\r\n## TypeError: <lambda>() missing 1 required positional argument: 'axis'\r\n\r\n\r\nCompare the result above with the result below\r\n\r\n```python\r\ndat['carat'].groupby(dat['color']).agg(np.mean), \r\ndat['carat'].groupby(dat['color']).agg(np.mean, axis=0), \r\ndat['carat'].groupby(dat['color']).agg('mean'), \r\ndat['carat'].groupby(dat['color']).agg(lambda x: np.mean(x)), \r\ndat['carat'].groupby(dat['color']).agg(lambda x, axis: np.mean(x, axis=axis), axis=0)\r\n## <all the same here>\r\n## color\r\n## A    0.22\r\n## E    0.26\r\n## J    0.31\r\n## Name: carat, dtype: float64,\r\n##\r\n##\r\n```\r\n\r\nCall it bug or inconsistency or poor design?\r\n\r\n\r\n### Issue Description\r\n\r\nBasically, in consistency's term,  `pd.Series.agg()` and `pd.Series.groupby().agg()` should act the same way.\r\n\r\nAnyway as I read the the code(the code is in the bottom), I found parameter axis for `Series.aggregate()` seems useless(or am I missing something here?)\r\n\r\nEven if it really needs a named paramter, it'd better be named something like `_axis_` to avoid conflicting names with \r\nfunctions to apply. For example `np.mean()` has a parameter named `axis=` and user might name a parameter `axis` (for example, `lambda x, axis: np.mean(x, axis=axis)`). \r\n\r\nAs far as I know, we do not need `axis=0` and ` self._get_axis_number(axis)` for Series at least(DataFrame has similar signature, and I think it should be renamed to something like `_axis_` or `_axis` or `__axis__`).\r\n\r\nSo I propose deleting `axis` parameter from Series.aggregate and renaming `axis` to `_axis` for DataFrame.aggreate.\r\n\r\n```\r\n    def aggregate(self, func=None, axis=0, *args, **kwargs):\r\n        # Validate the axis parameter\r\n        self._get_axis_number(axis)\r\n\r\n        # if func is None, will switch to user-provided \"named aggregation\" kwargs\r\n        if func is None:\r\n            func = dict(kwargs.items())\r\n\r\n        op = SeriesApply(self, func, convert_dtype=False, args=args, kwargs=kwargs)\r\n        result = op.agg()\r\n        return result\r\n```\r\n\r\n### Expected Behavior\r\n\r\n`dat['carat'].groupby(dat['color']).agg(lambda x: np.mean(x))` and\r\n`dat['carat']..agg(lambda x: np.mean(x))` works similarly\r\n\r\n### Installed Versions\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.8.12.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19044\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : Korean_Korea.949\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.22.2\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 22.0.3\r\nsetuptools       : 60.9.3\r\nCython           : 0.29.28\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.8.0\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.0.1\r\npandas_datareader: None\r\nbs4              : 4.10.0\r\nbottleneck       : None\r\nfastparquet      : None\r\nfsspec           : 2022.02.0\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : None\r\nnumexpr          : 2.8.1\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : 1.0.9\r\ns3fs             : None\r\nscipy            : 1.8.0\r\nsqlalchemy       : None\r\ntables           : 3.7.0\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 2.0.1\r\nxlwt             : None\r\nzstandard        : None\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46581/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46581/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46580","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46580/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46580/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46580/events","html_url":"https://github.com/pandas-dev/pandas/issues/46580","id":1187761681,"node_id":"I_kwDOAA0YD85Gy84R","number":46580,"title":"BUG: Reading a subset of columns with read_fwf fails if names are given when widths argument is used","user":{"login":"xnx","id":371774,"node_id":"MDQ6VXNlcjM3MTc3NA==","avatar_url":"https://avatars.githubusercontent.com/u/371774?v=4","gravatar_id":"","url":"https://api.github.com/users/xnx","html_url":"https://github.com/xnx","followers_url":"https://api.github.com/users/xnx/followers","following_url":"https://api.github.com/users/xnx/following{/other_user}","gists_url":"https://api.github.com/users/xnx/gists{/gist_id}","starred_url":"https://api.github.com/users/xnx/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/xnx/subscriptions","organizations_url":"https://api.github.com/users/xnx/orgs","repos_url":"https://api.github.com/users/xnx/repos","events_url":"https://api.github.com/users/xnx/events{/privacy}","received_events_url":"https://api.github.com/users/xnx/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-31T09:15:13Z","updated_at":"2022-03-31T09:15:13Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nfrom io import StringIO\r\nimport pandas as pd\r\n\r\ntest_data = StringIO(\"\"\"0  1    n -0.4100.1     4.6\r\n0  2    p  0.2 90.1     4.7\r\n0  3    n -0.3140.4    14.8\"\"\")\r\n\r\nwidths = (3, 5, 1, 5, 5, 8)\r\nusecols = (0, 1, 3, 5)\r\ncol_names = ('c0', 'c1', 'c3', 'c5')\r\ndf = pd.read_fwf(test_data, header=None, usecols=usecols, widths=widths,\r\n            index_col=False, names=col_names)\r\nprint(df)\n```\n\n\n### Issue Description\n\nIf the `widths` argument is passed to `read_fwf` instead of `colspecs` when a subset of the columns is requested (and they are named using the `names` arugment) a `ValueError: Length of colspecs must match length of names` is raised.\r\n\r\nThis didn't happen in 1.3 and seems to have been introduced by https://github.com/pandas-dev/pandas/pull/42920 – that one fixed an issue of `len(colspecs)` not matching `len(names)` but when `widths` is used instead, `colspecs` is built from all the column widths (including the ones not needed) and leads to a mismatch in lengths.\r\n\r\nA work-around is to not set the column names in the `read_fwf` call but to do it afterwards with `df.columns = ('c0', 'c1', 'c3', 'c5')`.\n\n### Expected Behavior\n\nIt should work as before: the above code should return the DataFrame\r\n```\r\n   c0  c1   c3    c5\r\n0   0   1 -0.4   4.6\r\n1   0   2  0.2   4.7\r\n2   0   3 -0.3  14.8\r\n```\n\n### Installed Versions\n\n<details>\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.9.1.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 21.2.0\r\nVersion          : Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_GB.UTF-8\r\nLOCALE           : en_GB.UTF-8\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.22.2\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\npip              : 22.0.3\r\nsetuptools       : 52.0.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.0.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.8.0\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46580/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46580/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46579","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46579/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46579/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46579/events","html_url":"https://github.com/pandas-dev/pandas/issues/46579","id":1187594420,"node_id":"I_kwDOAA0YD85GyUC0","number":46579,"title":"BUG: inconsistent behavior of `pd.Series.astype(\"datetime64\")` for concatenated 2 heterogenous `pd.Series` with equal `pd.Timestamp` and `datetime.date` values and more than 50 elements","user":{"login":"lycantropos","id":15193952,"node_id":"MDQ6VXNlcjE1MTkzOTUy","avatar_url":"https://avatars.githubusercontent.com/u/15193952?v=4","gravatar_id":"","url":"https://api.github.com/users/lycantropos","html_url":"https://github.com/lycantropos","followers_url":"https://api.github.com/users/lycantropos/followers","following_url":"https://api.github.com/users/lycantropos/following{/other_user}","gists_url":"https://api.github.com/users/lycantropos/gists{/gist_id}","starred_url":"https://api.github.com/users/lycantropos/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lycantropos/subscriptions","organizations_url":"https://api.github.com/users/lycantropos/orgs","repos_url":"https://api.github.com/users/lycantropos/repos","events_url":"https://api.github.com/users/lycantropos/events{/privacy}","received_events_url":"https://api.github.com/users/lycantropos/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-31T06:44:36Z","updated_at":"2022-03-31T07:45:48Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [x] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport datetime\r\nimport pandas as pd\r\n\r\n# runs fine with 50 elements\r\n(pd.concat([pd.Series([pd.Timestamp('2022-03-17 00:00:00')]), pd.Series([datetime.date(2022, 3, 17)] * 49)],\r\n           join='outer')\r\n .astype('datetime64'))\r\n# fails with 51 elements\r\n(pd.concat([pd.Series([pd.Timestamp('2022-03-17 00:00:00')]), pd.Series([datetime.date(2022, 3, 17)] * 50)],\r\n           join='outer')\r\n .astype('datetime64'))\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nIf we `pd.concat` 2 non-empty `pd.Series` one having `pd.Timestamp` and other having `datetime.date` equal values (representing the same date) such that sum of their sizes is more than 50 then we will have\r\n```bash\r\nTraceback (most recent call last):\r\n  File \"/path/to/python3.9.10/lib/python3.9/code.py\", line 90, in runcode\r\n    exec(code, self.locals)\r\n  File \"<input>\", line 5, in <module>\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/generic.py\", line 5920, in astype\r\n    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/internals/managers.py\", line 419, in astype\r\n    return self.apply(\"astype\", dtype=dtype, copy=copy, errors=errors)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/internals/managers.py\", line 304, in apply\r\n    applied = getattr(b, f)(**kwargs)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/internals/blocks.py\", line 580, in astype\r\n    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/dtypes/cast.py\", line 1292, in astype_array_safe\r\n    new_values = astype_array(values, dtype, copy=copy)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/dtypes/cast.py\", line 1237, in astype_array\r\n    values = astype_nansafe(values, dtype, copy=copy)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/dtypes/cast.py\", line 1163, in astype_nansafe\r\n    to_datetime(arr).values,\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/tools/datetimes.py\", line 1074, in to_datetime\r\n    result = _convert_and_box_cache(arg, cache_array)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/tools/datetimes.py\", line 256, in _convert_and_box_cache\r\n    result = Series(arg).map(cache_array)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/series.py\", line 4237, in map\r\n    new_values = self._map_values(arg, na_action=na_action)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/base.py\", line 852, in _map_values\r\n    indexer = mapper.index.get_indexer(values)\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3764, in get_indexer\r\n    return pself.get_indexer(\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 3721, in get_indexer\r\n    raise InvalidIndexError(self._requires_unique_msg)\r\npandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects\r\n```\r\nbut if we do the same for 50 values or less than no exception is raised.\r\n\r\n### Expected Behavior\r\n\r\nboth should fail or both should succeed independent on the number of values\r\n\r\n### Installed Versions\r\n\r\n`pd.show_versions()` fails with\r\n```bash\r\n>>> import pandas as pd\r\n>>> pd.show_versions()\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/util/_print_versions.py\", line 109, in show_versions\r\n    deps = _get_dependency_info()\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/util/_print_versions.py\", line 88, in _get_dependency_info\r\n    mod = import_optional_dependency(modname, errors=\"ignore\")\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/pandas/compat/_optional.py\", line 126, in import_optional_dependency\r\n    module = importlib.import_module(name)\r\n  File \"/path/to/python3.9.10/lib/python3.9/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/setuptools/__init__.py\", line 8, in <module>\r\n    import _distutils_hack.override  # noqa: F401\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/_distutils_hack/override.py\", line 1, in <module>\r\n    __import__('_distutils_hack').do_override()\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/_distutils_hack/__init__.py\", line 72, in do_override\r\n    ensure_local_distutils()\r\n  File \"/path/to/python3.9.10/lib/python3.9/site-packages/_distutils_hack/__init__.py\", line 59, in ensure_local_distutils\r\n    assert '_distutils' in core.__file__, core.__file__\r\nAssertionError: /path/to/python3.9.10/lib/python3.9/distutils/core.py\r\n```\r\n\r\nso my environment is\r\n- macOs 12.3 (21E230), Apple M1 Pro (but it reproduces inside `python:3.9.10` Docker container)\r\n- Python3.9.10\r\n- `pandas==1.4.1`\r\n\r\nInside Docker\r\n```python\r\n>>> import pandas as pd\r\n>>> pd.show_versions()\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.9.10.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.10.104-linuxkit\r\nVersion          : #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022\r\nmachine          : aarch64\r\nprocessor        : \r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.22.3\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 58.1.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n```","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46579/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46579/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46575","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46575/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46575/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46575/events","html_url":"https://github.com/pandas-dev/pandas/issues/46575","id":1186838909,"node_id":"I_kwDOAA0YD85Gvbl9","number":46575,"title":"BUG: DataFrame.dropna must not allow to set both how= and thresh= parameters","user":{"login":"arnaudlegout","id":7670869,"node_id":"MDQ6VXNlcjc2NzA4Njk=","avatar_url":"https://avatars.githubusercontent.com/u/7670869?v=4","gravatar_id":"","url":"https://api.github.com/users/arnaudlegout","html_url":"https://github.com/arnaudlegout","followers_url":"https://api.github.com/users/arnaudlegout/followers","following_url":"https://api.github.com/users/arnaudlegout/following{/other_user}","gists_url":"https://api.github.com/users/arnaudlegout/gists{/gist_id}","starred_url":"https://api.github.com/users/arnaudlegout/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/arnaudlegout/subscriptions","organizations_url":"https://api.github.com/users/arnaudlegout/orgs","repos_url":"https://api.github.com/users/arnaudlegout/repos","events_url":"https://api.github.com/users/arnaudlegout/events{/privacy}","received_events_url":"https://api.github.com/users/arnaudlegout/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-30T18:35:38Z","updated_at":"2022-03-30T18:35:38Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nIn [62]: p = pd.DataFrame([[1, 2, np.nan], [3, np.nan, np.nan], [7, 5, np.nan]])\r\n\r\nIn [63]: p\r\nOut[63]:\r\n   0    1   2\r\n0  1  2.0 NaN\r\n1  3  NaN NaN\r\n2  7  5.0 NaN\r\n\r\nIn [75]: p.dropna(how='all', axis=0)\r\nOut[75]:\r\n   0    1   2\r\n0  1  2.0 NaN\r\n1  3  NaN NaN\r\n2  7  5.0 NaN\r\n\r\nIn [76]: p.dropna(how='all', thresh=2, axis=0)\r\nOut[76]:\r\n   0    1   2\r\n0  1  2.0 NaN\r\n2  7  5.0 NaN\n```\n\n\n### Issue Description\n\n`DataFrame.dropna` has two incompatible parameters `thresh` and `how`, setting them together must raise an exception. Currently, when they are both set, `thresh` preempts on `how`. \n\n### Expected Behavior\n\nSetting both `thresh` and `how` on `DataFrame.dropna` must raise an exception. The documentation must be updated accordingly. \n\n### Installed Versions\n\n<details>\r\n\r\nIn [77]: pd.show_versions()\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.10.0.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19044\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : fr_FR.cp1252\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.21.5\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 58.0.4\r\nCython           : 0.29.25\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.8.0\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.1.1\r\npandas_datareader: 0.10.0\r\nbs4              : None\r\nbottleneck       : 1.3.2\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : 0.55.0\r\nnumexpr          : 2.8.1\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 7.0.0\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.7.3\r\nsqlalchemy       : 1.4.27\r\ntables           : None\r\ntabulate         : 0.8.9\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46575/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46575/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46574","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46574/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46574/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46574/events","html_url":"https://github.com/pandas-dev/pandas/issues/46574","id":1186789285,"node_id":"I_kwDOAA0YD85GvPel","number":46574,"title":"BUG: SettingWithCopyWarning should be raised on this Series assignement s.loc[label].iloc[ind] = val","user":{"login":"arnaudlegout","id":7670869,"node_id":"MDQ6VXNlcjc2NzA4Njk=","avatar_url":"https://avatars.githubusercontent.com/u/7670869?v=4","gravatar_id":"","url":"https://api.github.com/users/arnaudlegout","html_url":"https://github.com/arnaudlegout","followers_url":"https://api.github.com/users/arnaudlegout/followers","following_url":"https://api.github.com/users/arnaudlegout/following{/other_user}","gists_url":"https://api.github.com/users/arnaudlegout/gists{/gist_id}","starred_url":"https://api.github.com/users/arnaudlegout/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/arnaudlegout/subscriptions","organizations_url":"https://api.github.com/users/arnaudlegout/orgs","repos_url":"https://api.github.com/users/arnaudlegout/repos","events_url":"https://api.github.com/users/arnaudlegout/events{/privacy}","received_events_url":"https://api.github.com/users/arnaudlegout/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-30T17:46:32Z","updated_at":"2022-03-30T17:46:32Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nIn [21]: import pandas as pd\r\n\r\nIn [22]: pd.__version__\r\nOut[22]: '1.4.1'\r\n\r\nIn [23]: s = pd.Series([1, 2, 3, 10], index=['a', 'b', 'c', 'a'])\r\n\r\nIn [24]: s\r\nOut[24]:\r\na     1\r\nb     2\r\nc     3\r\na    10\r\ndtype: int64\r\n\r\nIn [26]: s.loc['a'].iloc[-1] = 0\r\n\r\nIn [27]: s\r\nOut[27]:\r\na     1\r\nb     2\r\nc     3\r\na    10\r\ndtype: int64\n```\n\n\n### Issue Description\n\nOn the line `s.loc['a'].iloc[-1] = 0`  there is no warning, and the assignment fails. \r\n\r\nThis issue has been reported in a comment of this other issue: https://github.com/pandas-dev/pandas/issues/37333\r\n\r\nAs issue 37333 does not describe this problem, I decided to create a new more explicit issue on this problem.\n\n### Expected Behavior\n\nOn the line `s.loc['a'].iloc[-1] = 0` a SettingWithCopyWarning must be raised. \n\n### Installed Versions\n\n<details>\r\n\r\nIn [29]: pd.show_versions()\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.10.0.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19044\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : fr_FR.cp1252\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.21.5\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 58.0.4\r\nCython           : 0.29.25\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.8.0\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.1.1\r\npandas_datareader: 0.10.0\r\nbs4              : None\r\nbottleneck       : 1.3.2\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : 0.55.0\r\nnumexpr          : 2.8.1\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 7.0.0\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.7.3\r\nsqlalchemy       : 1.4.27\r\ntables           : None\r\ntabulate         : 0.8.9\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46574/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46574/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46573","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46573/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46573/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46573/events","html_url":"https://github.com/pandas-dev/pandas/issues/46573","id":1186412852,"node_id":"I_kwDOAA0YD85Gtzk0","number":46573,"title":"BUG: prod and groupby.prod behave differently","user":{"login":"tf401","id":43294908,"node_id":"MDQ6VXNlcjQzMjk0OTA4","avatar_url":"https://avatars.githubusercontent.com/u/43294908?v=4","gravatar_id":"","url":"https://api.github.com/users/tf401","html_url":"https://github.com/tf401","followers_url":"https://api.github.com/users/tf401/followers","following_url":"https://api.github.com/users/tf401/following{/other_user}","gists_url":"https://api.github.com/users/tf401/gists{/gist_id}","starred_url":"https://api.github.com/users/tf401/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tf401/subscriptions","organizations_url":"https://api.github.com/users/tf401/orgs","repos_url":"https://api.github.com/users/tf401/repos","events_url":"https://api.github.com/users/tf401/events{/privacy}","received_events_url":"https://api.github.com/users/tf401/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":{"login":"mctessi","id":100441021,"node_id":"U_kgDOBfybvQ","avatar_url":"https://avatars.githubusercontent.com/u/100441021?v=4","gravatar_id":"","url":"https://api.github.com/users/mctessi","html_url":"https://github.com/mctessi","followers_url":"https://api.github.com/users/mctessi/followers","following_url":"https://api.github.com/users/mctessi/following{/other_user}","gists_url":"https://api.github.com/users/mctessi/gists{/gist_id}","starred_url":"https://api.github.com/users/mctessi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mctessi/subscriptions","organizations_url":"https://api.github.com/users/mctessi/orgs","repos_url":"https://api.github.com/users/mctessi/repos","events_url":"https://api.github.com/users/mctessi/events{/privacy}","received_events_url":"https://api.github.com/users/mctessi/received_events","type":"User","site_admin":false},"assignees":[{"login":"mctessi","id":100441021,"node_id":"U_kgDOBfybvQ","avatar_url":"https://avatars.githubusercontent.com/u/100441021?v=4","gravatar_id":"","url":"https://api.github.com/users/mctessi","html_url":"https://github.com/mctessi","followers_url":"https://api.github.com/users/mctessi/followers","following_url":"https://api.github.com/users/mctessi/following{/other_user}","gists_url":"https://api.github.com/users/mctessi/gists{/gist_id}","starred_url":"https://api.github.com/users/mctessi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mctessi/subscriptions","organizations_url":"https://api.github.com/users/mctessi/orgs","repos_url":"https://api.github.com/users/mctessi/repos","events_url":"https://api.github.com/users/mctessi/events{/privacy}","received_events_url":"https://api.github.com/users/mctessi/received_events","type":"User","site_admin":false}],"milestone":null,"comments":7,"created_at":"2022-03-30T12:50:12Z","updated_at":"2022-03-31T19:42:03Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\n\r\ndf = pd.DataFrame(\r\n    data=[\r\n        [5,\t2, 17, 11, 7, 2, 3],\r\n        [5,\t2, 17, 41, 7, 2, 3],\r\n        [5,\t2, 17, 17, 7, 2, 3],\r\n        [5,\t2, 17, 37, 7, 2, 3],\r\n        [5,\t2, 17, 7, 7, 2, 3],\r\n        [5,\t2, 17, 29, 7, 2, 3],\r\n        [5,\t2, 17, 31, 7, 2, 3],\r\n        [5,\t2, 17, 2, 7, 2, 3],\r\n        [5,\t2, 17, 3, 7, 2, 3],\r\n        [5,\t2, 17, 43, 7, 2, 3],\r\n        [5,\t2, 17, 5, 7, 2, 3],\r\n        [5,\t2, 17, 47, 7, 2, 3],\r\n        [5,\t2, 17, 19, 7, 2, 3],\r\n        [5,\t2, 17, 23, 7, 2, 3],\r\n\r\n    ],\r\n    columns=['A','B','C','D','E','F','G']\r\n)\r\n\r\ndf.prod()\r\n#A            6103515625\r\n#B                 16384\r\n#C    168377826559400929\r\n#D     47299214045268570 <-- correct value\r\n#E          678223072849\r\n#F                 16384\r\n#G               4782969\r\n#dtype: int64\r\n\r\ndf.groupby(['A','B','C','E','F','G']).prod()\r\n\r\n#\t\t\t\t\t\tD\r\n#A\tB\tC\tE\tF\tG\t\r\n#5\t2\t17\t7\t2\t3\t47299214045268568 <-- wrong value\n```\n\n\n### Issue Description\n\nDuring a project that uses pandas groupby prod method I noticed possible bug.\r\n\r\nThe reproducible example should be clear but the core issue is that is seems that pandas prod() method behaves different\r\nthan pandas groupby prod method. The result is inconsistent. In the example, please inspect column \"D\"\n\n### Expected Behavior\n\nCorrect output of column D during the groupby operation\n\n### Installed Versions\n\n<details>\r\n\r\n'1.4.1'\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46573/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46573/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46571","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46571/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46571/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46571/events","html_url":"https://github.com/pandas-dev/pandas/issues/46571","id":1186031610,"node_id":"I_kwDOAA0YD85GsWf6","number":46571,"title":"ENH: Allow usage of custom library to serialize with `to_json` method.","user":{"login":"Duoquote","id":16341937,"node_id":"MDQ6VXNlcjE2MzQxOTM3","avatar_url":"https://avatars.githubusercontent.com/u/16341937?v=4","gravatar_id":"","url":"https://api.github.com/users/Duoquote","html_url":"https://github.com/Duoquote","followers_url":"https://api.github.com/users/Duoquote/followers","following_url":"https://api.github.com/users/Duoquote/following{/other_user}","gists_url":"https://api.github.com/users/Duoquote/gists{/gist_id}","starred_url":"https://api.github.com/users/Duoquote/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Duoquote/subscriptions","organizations_url":"https://api.github.com/users/Duoquote/orgs","repos_url":"https://api.github.com/users/Duoquote/repos","events_url":"https://api.github.com/users/Duoquote/events{/privacy}","received_events_url":"https://api.github.com/users/Duoquote/received_events","type":"User","site_admin":false},"labels":[{"id":76812,"node_id":"MDU6TGFiZWw3NjgxMg==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement","name":"Enhancement","color":"4E9A06","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-30T07:48:57Z","updated_at":"2022-03-30T07:48:57Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"#### Is your feature request related to a problem?\r\n\r\nI was thinking about if I can pass my custom function to pandas' `to_json` to use some other json serializer, or maybe somehow access the dictionary that `to_json` method generates, turns out you can not do both.\r\n\r\n#### Describe the solution you'd like\r\n\r\nAs seen [here](https://github.com/pandas-dev/pandas/blob/3b163de02f666a2342e18468cba7d6c286f526bf/pandas/io/json/_json.py#L69), the default `json.dumps` function is set hardcoded, a new argument can be added to `to_json` method like `serializer_function`.  So that I can use any other library like `orjson` and pass it like `df.to_json(serializer_function=orjson.dumps)`.","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46571/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46571/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46570","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46570/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46570/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46570/events","html_url":"https://github.com/pandas-dev/pandas/pull/46570","id":1185906280,"node_id":"PR_kwDOAA0YD841SPuI","number":46570,"title":"POC For docker compose","user":{"login":"WillAyd","id":609873,"node_id":"MDQ6VXNlcjYwOTg3Mw==","avatar_url":"https://avatars.githubusercontent.com/u/609873?v=4","gravatar_id":"","url":"https://api.github.com/users/WillAyd","html_url":"https://github.com/WillAyd","followers_url":"https://api.github.com/users/WillAyd/followers","following_url":"https://api.github.com/users/WillAyd/following{/other_user}","gists_url":"https://api.github.com/users/WillAyd/gists{/gist_id}","starred_url":"https://api.github.com/users/WillAyd/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/WillAyd/subscriptions","organizations_url":"https://api.github.com/users/WillAyd/orgs","repos_url":"https://api.github.com/users/WillAyd/repos","events_url":"https://api.github.com/users/WillAyd/events{/privacy}","received_events_url":"https://api.github.com/users/WillAyd/received_events","type":"User","site_admin":false},"labels":[{"id":48070600,"node_id":"MDU6TGFiZWw0ODA3MDYwMA==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/CI","name":"CI","color":"a2bca7","default":false,"description":"Continuous Integration"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2022-03-30T05:31:11Z","updated_at":"2022-03-31T20:08:00Z","closed_at":null,"author_association":"MEMBER","active_lock_reason":null,"draft":true,"pull_request":{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/46570","html_url":"https://github.com/pandas-dev/pandas/pull/46570","diff_url":"https://github.com/pandas-dev/pandas/pull/46570.diff","patch_url":"https://github.com/pandas-dev/pandas/pull/46570.patch","merged_at":null},"body":"- [X] closes #46532 \r\n\r\nPOC using docker compose, which is also used by the arrow project. \r\n\r\nThe idea here is that we can simply run `docker compose build db-testing` to build an image with postgres (can later add mysql) and our minimal development requirements then `docker compose run --rm db-testing` to run relevant tests. This can be done both by a developer as well as on GH actions.\r\n\r\nThis still needs a bit more work as it currently muddles user permissions on the host when building pandas\r\n\r\ncc @jonashaag who looks to have been doing some awesome work on CI lately","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46570/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46570/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46569","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46569/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46569/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46569/events","html_url":"https://github.com/pandas-dev/pandas/issues/46569","id":1185878561,"node_id":"I_kwDOAA0YD85GrxIh","number":46569,"title":"BUG:  ENH: Allow callable for on_bad_lines in read_csv when engine=\"python\" #45146","user":{"login":"kevinhodes","id":89279983,"node_id":"MDQ6VXNlcjg5Mjc5OTgz","avatar_url":"https://avatars.githubusercontent.com/u/89279983?v=4","gravatar_id":"","url":"https://api.github.com/users/kevinhodes","html_url":"https://github.com/kevinhodes","followers_url":"https://api.github.com/users/kevinhodes/followers","following_url":"https://api.github.com/users/kevinhodes/following{/other_user}","gists_url":"https://api.github.com/users/kevinhodes/gists{/gist_id}","starred_url":"https://api.github.com/users/kevinhodes/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kevinhodes/subscriptions","organizations_url":"https://api.github.com/users/kevinhodes/orgs","repos_url":"https://api.github.com/users/kevinhodes/repos","events_url":"https://api.github.com/users/kevinhodes/events{/privacy}","received_events_url":"https://api.github.com/users/kevinhodes/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":47229171,"node_id":"MDU6TGFiZWw0NzIyOTE3MQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV","name":"IO CSV","color":"5319e7","default":false,"description":"read_csv, to_csv"},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":10,"created_at":"2022-03-30T05:02:02Z","updated_at":"2022-03-30T22:45:23Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\n\r\nlst = []\r\n\r\n\r\ndef failed_line(bad_line: list[str]) -> list[str]:\r\n    print(\"failed line\")\r\n    lst.append(bad_line)\r\n    return lst\r\n\r\n\r\nif __name__ == '__main__':\r\n    dtypes = {\r\n        \"CV_CCT\": object,\r\n        \"C_NOMBRE\": object,\r\n        \"CV_TIPO\": float,\r\n        \"C_TIPO\": object,\r\n        \"CV_ADMINISTRATIVA\": object,\r\n        \"C_ADMINISTRATIVA\": object,\r\n        \"CV_ESTATUS\": int,\r\n        \"C_ESTATUS\": object,\r\n        \"F_FUNDACION\": object,\r\n        \"INMUEBLE_CV_INMUEBLE\": object,\r\n        \"INMUEBLE_CV_VIALIDAD_PRINCIPAL\": int,\r\n        \"INMUEBLE_C_VIALIDAD_PRINCIPAL\": object,\r\n        \"INMUEBLE_CV_VIALIDAD_DERECHA\": int,\r\n        \"INMUEBLE_C_VIALIDAD_DERECHA\": object,\r\n        \"INMUEBLE_CV_VIALIDAD_IZQUIERDA\": int,\r\n        \"INMUEBLE_C_VIALIDAD_IZQUIERDA\": object,\r\n        \"INMUEBLE_CV_VIALIDAD_POSTERIOR\": int,\r\n        \"INMUEBLE_C_VIALIDAD_POSTERIOR\": object,\r\n        \"INMUEBLE_N_EXTNUM\": int,\r\n        \"INMUEBLE_C_EXTALF\": object,\r\n        \"INMUEBLE_N_INTNUM\": int,\r\n        \"INMUEBLE_C_INTALF\": object,\r\n        \"INMUEBLE_CV_ENT\": object,\r\n        \"INMUEBLE_C_NOM_ENT\": object,\r\n        \"INMUEBLE_CV_MUN\": object,\r\n        \"INMUEBLE_C_NOM_MUN\": object,\r\n        \"INMUEBLE_CV_LOC\": object,\r\n        \"INMUEBLE_C_NOM_LOC\": object,\r\n        \"INMUEBLE_CV_ASEN\": object,\r\n        \"INMUEBLE_C_NOM_ASEN\": object,\r\n        \"INMUEBLE_CV_CODIGO_POSTAL\": object,\r\n        \"INMUEBLE_C_DESC_UBICACION\": object,\r\n        \"INMUEBLE_LATITUD\": float,\r\n        \"INMUEBLE_LONGITUD\": float,\r\n        \"SOSTENIMIENTO_CV_CONTROL\": int,\r\n        \"SOSTENIMIENTO_C_CONTROL\": object,\r\n        \"SOSTENIMIENTO_CV_SUBCONTROL\": int,\r\n        \"SOSTENIMIENTO_C_SUBCONTROL\": object,\r\n        \"SOSTENIMIENTO_CV_DEPENDENCIAN1\": int,\r\n        \"SOSTENIMIENTO_C_DEPENDENCIAN1\": object,\r\n        \"SOSTENIMIENTO_CV_DEPENDENCIAN2\": int,\r\n        \"SOSTENIMIENTO_C_DEPENDENCIAN2\": object,\r\n        \"SOSTENIMIENTO_CV_DEPENDENCIAN3\": int,\r\n        \"SOSTENIMIENTO_C_DEPENDENCIAN3\": object,\r\n        \"SOSTENIMIENTO_CV_DEPENDENCIAN4\": int,\r\n        \"SOSTENIMIENTO_C_DEPENDENCIAN4\": object,\r\n        \"SOSTENIMIENTO_CV_DEPENDENCIAN5\": int,\r\n        \"SOSTENIMIENTO_C_DEPENDENCIAN5\": object,\r\n        \"SOSTENIMIENTO_CV_SERVICIO\": object,\r\n        \"SOSTENIMIENTO_C_SERVICIO\": object,\r\n        \"DEPOPERATIVA_CV_DEPENDENCIAN1\": int,\r\n        \"DEPOPERATIVA_C_DEPENDENCIAN1\": object,\r\n        \"DEPOPERATIVA_CV_DEPENDENCIAN2\": int,\r\n        \"DEPOPERATIVA_C_DEPENDENCIAN2\": object,\r\n        \"DEPOPERATIVA_CV_DEPENDENCIAN3\": int,\r\n        \"DEPOPERATIVA_C_DEPENDENCIAN3\": object,\r\n        \"DEPOPERATIVA_CV_DEPENDENCIAN4\": int,\r\n        \"DEPOPERATIVA_C_DEPENDENCIAN4\": object,\r\n        \"DEPOPERATIVA_CV_DEPENDENCIAN5\": int,\r\n        \"DEPOPERATIVA_C_DEPENDENCIAN5\": object,\r\n        \"CONTACTO_CV_CARGO\": int,\r\n        \"CONTACTO_C_CARGO\": object,\r\n        \"CONTACTO_CV_TIPODIRECTOR\": int,\r\n        \"CONTACTO_C_TIPODIRECTOR\": object,\r\n        \"CONTACTO_C_ASOCIACION\": object,\r\n        \"CONTACTO_C_CURP\": object,\r\n        \"CONTACTO_C_RFC\": object,\r\n        \"CONTACTO_C_NOMBRE\": object,\r\n        \"CONTACTO_C_APELLIDO1\": object,\r\n        \"CONTACTO_C_APELLIDO2\": object,\r\n        \"CONTACTO_C_TELEFONO\": object,\r\n        \"CONTACTO_C_CELULAR\": object,\r\n        \"CONTACTO_C_EMAIL\": object,\r\n        \"CONTACTO_C_EXTENSION\": object,\r\n        \"CONTACTO_C_PWEB\": object,\r\n        \"SERREG_CV_CCT\": object,\r\n        \"JEFSEC_CV_CCT\": object,\r\n        \"SUPERVISION_CV_CCT\": object,\r\n        \"C_TUNO_1\": object,\r\n        \"C_TUNO_2\": object,\r\n        \"C_TUNO_3\": object,\r\n        \"TIPONIVELSUB_CV_SERVICION1\": int,\r\n        \"TIPONIVELSUB_C_SERVICION1\": object,\r\n        \"TIPONIVELSUB_CV_SERVICION2\": int,\r\n        \"TIPONIVELSUB_C_SERVICION2\": object,\r\n        \"TIPONIVELSUB_CV_SERVICION3\": int,\r\n        \"TIPONIVELSUB_C_SERVICION3\": object,\r\n        \"C_SERVICIO_CAM\": object,\r\n        \"CARACTERISTCA_CV_CARACTERIZAN1\": int,\r\n        \"CARACTERISTCA_C_CARACTERIZAN1\": object,\r\n        \"CARACTERISTCA_CV_CARACTERIZAN2\": int,\r\n        \"CARACTERISTCA_C_CARACTERIZAN2\": object,\r\n        \"Unnamed: 92\": object\r\n    }\r\n\r\n    df = pd.read_csv(\"cct15_bad.csv\", encoding='ansi', dtype=dtypes, on_bad_lines=failed_line, engine='python')\n```\n\n\n### Issue Description\n\nfailed_line() never gets fired.\n\n### Expected Behavior\n\nfailed_line() to get fired.\n\n### Installed Versions\n\n<details>\r\n\r\nWindows 10\r\npython 3.10\r\npandas 1.4.1\r\n\r\n</details>\r\n[cct15_bad.zip](https://github.com/pandas-dev/pandas/files/8377144/cct15_bad.zip)\r\n\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46569/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46569/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46568","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46568/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46568/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46568/events","html_url":"https://github.com/pandas-dev/pandas/pull/46568","id":1185785553,"node_id":"PR_kwDOAA0YD841R1wW","number":46568,"title":"CLN/TYP: assorted","user":{"login":"jbrockmendel","id":8078968,"node_id":"MDQ6VXNlcjgwNzg5Njg=","avatar_url":"https://avatars.githubusercontent.com/u/8078968?v=4","gravatar_id":"","url":"https://api.github.com/users/jbrockmendel","html_url":"https://github.com/jbrockmendel","followers_url":"https://api.github.com/users/jbrockmendel/followers","following_url":"https://api.github.com/users/jbrockmendel/following{/other_user}","gists_url":"https://api.github.com/users/jbrockmendel/gists{/gist_id}","starred_url":"https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jbrockmendel/subscriptions","organizations_url":"https://api.github.com/users/jbrockmendel/orgs","repos_url":"https://api.github.com/users/jbrockmendel/repos","events_url":"https://api.github.com/users/jbrockmendel/events{/privacy}","received_events_url":"https://api.github.com/users/jbrockmendel/received_events","type":"User","site_admin":false},"labels":[{"id":211029535,"node_id":"MDU6TGFiZWwyMTEwMjk1MzU=","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Clean","name":"Clean","color":"207de5","default":false,"description":null},{"id":1280988427,"node_id":"MDU6TGFiZWwxMjgwOTg4NDI3","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Typing","name":"Typing","color":"ea91a4","default":false,"description":"type annotations, mypy/pyright type checking"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pandas-dev/pandas/milestones/92","html_url":"https://github.com/pandas-dev/pandas/milestone/92","labels_url":"https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels","id":7530006,"node_id":"MI_kwDOAA0YD84AcuYW","number":92,"title":"1.5","description":"","creator":{"login":"jreback","id":953992,"node_id":"MDQ6VXNlcjk1Mzk5Mg==","avatar_url":"https://avatars.githubusercontent.com/u/953992?v=4","gravatar_id":"","url":"https://api.github.com/users/jreback","html_url":"https://github.com/jreback","followers_url":"https://api.github.com/users/jreback/followers","following_url":"https://api.github.com/users/jreback/following{/other_user}","gists_url":"https://api.github.com/users/jreback/gists{/gist_id}","starred_url":"https://api.github.com/users/jreback/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jreback/subscriptions","organizations_url":"https://api.github.com/users/jreback/orgs","repos_url":"https://api.github.com/users/jreback/repos","events_url":"https://api.github.com/users/jreback/events{/privacy}","received_events_url":"https://api.github.com/users/jreback/received_events","type":"User","site_admin":false},"open_issues":53,"closed_issues":600,"state":"open","created_at":"2021-12-31T21:51:13Z","updated_at":"2022-03-31T17:59:23Z","due_on":"2022-06-30T07:00:00Z","closed_at":null},"comments":2,"created_at":"2022-03-30T02:41:10Z","updated_at":"2022-03-31T20:06:28Z","closed_at":null,"author_association":"MEMBER","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/46568","html_url":"https://github.com/pandas-dev/pandas/pull/46568","diff_url":"https://github.com/pandas-dev/pandas/pull/46568.diff","patch_url":"https://github.com/pandas-dev/pandas/pull/46568.patch","merged_at":null},"body":null,"reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46568/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46568/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46565","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46565/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46565/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46565/events","html_url":"https://github.com/pandas-dev/pandas/pull/46565","id":1185340074,"node_id":"PR_kwDOAA0YD841QTBO","number":46565,"title":"TYP: setter for index/columns property-like (AxisProperty)","user":{"login":"simonjayhawkins","id":13159005,"node_id":"MDQ6VXNlcjEzMTU5MDA1","avatar_url":"https://avatars.githubusercontent.com/u/13159005?v=4","gravatar_id":"","url":"https://api.github.com/users/simonjayhawkins","html_url":"https://github.com/simonjayhawkins","followers_url":"https://api.github.com/users/simonjayhawkins/followers","following_url":"https://api.github.com/users/simonjayhawkins/following{/other_user}","gists_url":"https://api.github.com/users/simonjayhawkins/gists{/gist_id}","starred_url":"https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/simonjayhawkins/subscriptions","organizations_url":"https://api.github.com/users/simonjayhawkins/orgs","repos_url":"https://api.github.com/users/simonjayhawkins/repos","events_url":"https://api.github.com/users/simonjayhawkins/events{/privacy}","received_events_url":"https://api.github.com/users/simonjayhawkins/received_events","type":"User","site_admin":false},"labels":[{"id":1280988427,"node_id":"MDU6TGFiZWwxMjgwOTg4NDI3","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Typing","name":"Typing","color":"ea91a4","default":false,"description":"type annotations, mypy/pyright type checking"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-29T19:50:17Z","updated_at":"2022-03-30T16:30:51Z","closed_at":null,"author_association":"MEMBER","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/46565","html_url":"https://github.com/pandas-dev/pandas/pull/46565","diff_url":"https://github.com/pandas-dev/pandas/pull/46565.diff","patch_url":"https://github.com/pandas-dev/pandas/pull/46565.patch","merged_at":null},"body":null,"reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46565/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46565/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46564","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46564/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46564/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46564/events","html_url":"https://github.com/pandas-dev/pandas/pull/46564","id":1185191491,"node_id":"PR_kwDOAA0YD841Pzhq","number":46564,"title":"Don't run GHA CI for Azure changes and vice-versa","user":{"login":"jonashaag","id":175722,"node_id":"MDQ6VXNlcjE3NTcyMg==","avatar_url":"https://avatars.githubusercontent.com/u/175722?v=4","gravatar_id":"","url":"https://api.github.com/users/jonashaag","html_url":"https://github.com/jonashaag","followers_url":"https://api.github.com/users/jonashaag/followers","following_url":"https://api.github.com/users/jonashaag/following{/other_user}","gists_url":"https://api.github.com/users/jonashaag/gists{/gist_id}","starred_url":"https://api.github.com/users/jonashaag/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jonashaag/subscriptions","organizations_url":"https://api.github.com/users/jonashaag/orgs","repos_url":"https://api.github.com/users/jonashaag/repos","events_url":"https://api.github.com/users/jonashaag/events{/privacy}","received_events_url":"https://api.github.com/users/jonashaag/received_events","type":"User","site_admin":false},"labels":[{"id":48070600,"node_id":"MDU6TGFiZWw0ODA3MDYwMA==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/CI","name":"CI","color":"a2bca7","default":false,"description":"Continuous Integration"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pandas-dev/pandas/milestones/94","html_url":"https://github.com/pandas-dev/pandas/milestone/94","labels_url":"https://api.github.com/repos/pandas-dev/pandas/milestones/94/labels","id":7667127,"node_id":"MI_kwDOAA0YD84AdP23","number":94,"title":"1.4.2","description":"on-merge: backport to 1.4.x","creator":{"login":"simonjayhawkins","id":13159005,"node_id":"MDQ6VXNlcjEzMTU5MDA1","avatar_url":"https://avatars.githubusercontent.com/u/13159005?v=4","gravatar_id":"","url":"https://api.github.com/users/simonjayhawkins","html_url":"https://github.com/simonjayhawkins","followers_url":"https://api.github.com/users/simonjayhawkins/followers","following_url":"https://api.github.com/users/simonjayhawkins/following{/other_user}","gists_url":"https://api.github.com/users/simonjayhawkins/gists{/gist_id}","starred_url":"https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/simonjayhawkins/subscriptions","organizations_url":"https://api.github.com/users/simonjayhawkins/orgs","repos_url":"https://api.github.com/users/simonjayhawkins/repos","events_url":"https://api.github.com/users/simonjayhawkins/events{/privacy}","received_events_url":"https://api.github.com/users/simonjayhawkins/received_events","type":"User","site_admin":false},"open_issues":8,"closed_issues":97,"state":"open","created_at":"2022-02-11T09:43:27Z","updated_at":"2022-03-31T18:01:23Z","due_on":"2022-03-05T08:00:00Z","closed_at":null},"comments":1,"created_at":"2022-03-29T17:30:41Z","updated_at":"2022-03-30T13:00:55Z","closed_at":null,"author_association":"CONTRIBUTOR","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/46564","html_url":"https://github.com/pandas-dev/pandas/pull/46564","diff_url":"https://github.com/pandas-dev/pandas/pull/46564.diff","patch_url":"https://github.com/pandas-dev/pandas/pull/46564.patch","merged_at":null},"body":"- [ ] closes #xxxx (Replace xxxx with the Github issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46564/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46564/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46562","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46562/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46562/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46562/events","html_url":"https://github.com/pandas-dev/pandas/pull/46562","id":1184896816,"node_id":"PR_kwDOAA0YD841O1Mm","number":46562,"title":"tocsv_interval _categories","user":{"login":"Kyrpel","id":66919765,"node_id":"MDQ6VXNlcjY2OTE5NzY1","avatar_url":"https://avatars.githubusercontent.com/u/66919765?v=4","gravatar_id":"","url":"https://api.github.com/users/Kyrpel","html_url":"https://github.com/Kyrpel","followers_url":"https://api.github.com/users/Kyrpel/followers","following_url":"https://api.github.com/users/Kyrpel/following{/other_user}","gists_url":"https://api.github.com/users/Kyrpel/gists{/gist_id}","starred_url":"https://api.github.com/users/Kyrpel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Kyrpel/subscriptions","organizations_url":"https://api.github.com/users/Kyrpel/orgs","repos_url":"https://api.github.com/users/Kyrpel/repos","events_url":"https://api.github.com/users/Kyrpel/events{/privacy}","received_events_url":"https://api.github.com/users/Kyrpel/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-29T13:43:10Z","updated_at":"2022-03-31T07:17:56Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/46562","html_url":"https://github.com/pandas-dev/pandas/pull/46562","diff_url":"https://github.com/pandas-dev/pandas/pull/46562.diff","patch_url":"https://github.com/pandas-dev/pandas/pull/46562.patch","merged_at":null},"body":"- [x] closes #46297\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46562/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46562/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46561","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46561/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46561/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46561/events","html_url":"https://github.com/pandas-dev/pandas/issues/46561","id":1184875189,"node_id":"I_kwDOAA0YD85Gn8K1","number":46561,"title":"STYLE: add check to keep `black` version in sync between `.pre-commit-config.yaml` and `environment.yaml`","user":{"login":"MarcoGorelli","id":33491632,"node_id":"MDQ6VXNlcjMzNDkxNjMy","avatar_url":"https://avatars.githubusercontent.com/u/33491632?v=4","gravatar_id":"","url":"https://api.github.com/users/MarcoGorelli","html_url":"https://github.com/MarcoGorelli","followers_url":"https://api.github.com/users/MarcoGorelli/followers","following_url":"https://api.github.com/users/MarcoGorelli/following{/other_user}","gists_url":"https://api.github.com/users/MarcoGorelli/gists{/gist_id}","starred_url":"https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/MarcoGorelli/subscriptions","organizations_url":"https://api.github.com/users/MarcoGorelli/orgs","repos_url":"https://api.github.com/users/MarcoGorelli/repos","events_url":"https://api.github.com/users/MarcoGorelli/events{/privacy}","received_events_url":"https://api.github.com/users/MarcoGorelli/received_events","type":"User","site_admin":false},"labels":[{"id":106935113,"node_id":"MDU6TGFiZWwxMDY5MzUxMTM=","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Code%20Style","name":"Code Style","color":"eb6420","default":false,"description":"Code style, linting, code_checks"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2022-03-29T13:28:45Z","updated_at":"2022-03-29T22:31:03Z","closed_at":null,"author_association":"MEMBER","active_lock_reason":null,"body":"Might be possible to adapt\r\n\r\nhttps://github.com/pandas-dev/pandas/blob/3cb70a5f0d1dc386f7806fca75abff6f098b1539/scripts/sync_flake8_versions.py\r\n\r\nfor this\r\n\r\nTask is to have a check which makes sure that the `black` version here\r\n\r\nhttps://github.com/pandas-dev/pandas/blob/3cb70a5f0d1dc386f7806fca75abff6f098b1539/.pre-commit-config.yaml#L19\r\n\r\nand here\r\n\r\nhttps://github.com/pandas-dev/pandas/blob/3cb70a5f0d1dc386f7806fca75abff6f098b1539/environment.yml#L21\r\n\r\nare in sync","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46561/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46561/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46560","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46560/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46560/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46560/events","html_url":"https://github.com/pandas-dev/pandas/issues/46560","id":1184857243,"node_id":"I_kwDOAA0YD85Gn3yb","number":46560,"title":"API: numeric_only consistency","user":{"login":"rhshadrach","id":45562402,"node_id":"MDQ6VXNlcjQ1NTYyNDAy","avatar_url":"https://avatars.githubusercontent.com/u/45562402?v=4","gravatar_id":"","url":"https://api.github.com/users/rhshadrach","html_url":"https://github.com/rhshadrach","followers_url":"https://api.github.com/users/rhshadrach/followers","following_url":"https://api.github.com/users/rhshadrach/following{/other_user}","gists_url":"https://api.github.com/users/rhshadrach/gists{/gist_id}","starred_url":"https://api.github.com/users/rhshadrach/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rhshadrach/subscriptions","organizations_url":"https://api.github.com/users/rhshadrach/orgs","repos_url":"https://api.github.com/users/rhshadrach/repos","events_url":"https://api.github.com/users/rhshadrach/events{/privacy}","received_events_url":"https://api.github.com/users/rhshadrach/received_events","type":"User","site_admin":false},"labels":[{"id":1741841389,"node_id":"MDU6TGFiZWwxNzQxODQxMzg5","url":"https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency","name":"API - Consistency","color":"b60205","default":false,"description":"Internal Consistency of API/Behavior"},{"id":2365523662,"node_id":"MDU6TGFiZWwyMzY1NTIzNjYy","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Nuisance%20Columns","name":"Nuisance Columns","color":"120491","default":false,"description":"Identifying/Dropping nuisance columns in reductions, groupby.add, DataFrame.apply"}],"state":"open","locked":false,"assignee":{"login":"rhshadrach","id":45562402,"node_id":"MDQ6VXNlcjQ1NTYyNDAy","avatar_url":"https://avatars.githubusercontent.com/u/45562402?v=4","gravatar_id":"","url":"https://api.github.com/users/rhshadrach","html_url":"https://github.com/rhshadrach","followers_url":"https://api.github.com/users/rhshadrach/followers","following_url":"https://api.github.com/users/rhshadrach/following{/other_user}","gists_url":"https://api.github.com/users/rhshadrach/gists{/gist_id}","starred_url":"https://api.github.com/users/rhshadrach/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rhshadrach/subscriptions","organizations_url":"https://api.github.com/users/rhshadrach/orgs","repos_url":"https://api.github.com/users/rhshadrach/repos","events_url":"https://api.github.com/users/rhshadrach/events{/privacy}","received_events_url":"https://api.github.com/users/rhshadrach/received_events","type":"User","site_admin":false},"assignees":[{"login":"rhshadrach","id":45562402,"node_id":"MDQ6VXNlcjQ1NTYyNDAy","avatar_url":"https://avatars.githubusercontent.com/u/45562402?v=4","gravatar_id":"","url":"https://api.github.com/users/rhshadrach","html_url":"https://github.com/rhshadrach","followers_url":"https://api.github.com/users/rhshadrach/followers","following_url":"https://api.github.com/users/rhshadrach/following{/other_user}","gists_url":"https://api.github.com/users/rhshadrach/gists{/gist_id}","starred_url":"https://api.github.com/users/rhshadrach/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rhshadrach/subscriptions","organizations_url":"https://api.github.com/users/rhshadrach/orgs","repos_url":"https://api.github.com/users/rhshadrach/repos","events_url":"https://api.github.com/users/rhshadrach/events{/privacy}","received_events_url":"https://api.github.com/users/rhshadrach/received_events","type":"User","site_admin":false}],"milestone":{"url":"https://api.github.com/repos/pandas-dev/pandas/milestones/92","html_url":"https://github.com/pandas-dev/pandas/milestone/92","labels_url":"https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels","id":7530006,"node_id":"MI_kwDOAA0YD84AcuYW","number":92,"title":"1.5","description":"","creator":{"login":"jreback","id":953992,"node_id":"MDQ6VXNlcjk1Mzk5Mg==","avatar_url":"https://avatars.githubusercontent.com/u/953992?v=4","gravatar_id":"","url":"https://api.github.com/users/jreback","html_url":"https://github.com/jreback","followers_url":"https://api.github.com/users/jreback/followers","following_url":"https://api.github.com/users/jreback/following{/other_user}","gists_url":"https://api.github.com/users/jreback/gists{/gist_id}","starred_url":"https://api.github.com/users/jreback/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jreback/subscriptions","organizations_url":"https://api.github.com/users/jreback/orgs","repos_url":"https://api.github.com/users/jreback/repos","events_url":"https://api.github.com/users/jreback/events{/privacy}","received_events_url":"https://api.github.com/users/jreback/received_events","type":"User","site_admin":false},"open_issues":53,"closed_issues":600,"state":"open","created_at":"2021-12-31T21:51:13Z","updated_at":"2022-03-31T17:59:23Z","due_on":"2022-06-30T07:00:00Z","closed_at":null},"comments":0,"created_at":"2022-03-29T13:16:09Z","updated_at":"2022-03-29T13:21:52Z","closed_at":null,"author_association":"MEMBER","active_lock_reason":null,"body":"Tracking issue for API consistency between all the different ops that have a numeric_only argument. This includes the dtype of the return when object types are present. I plan to report on the current state after #46524 and #46072 are closed and prior to the 1.5 release.\r\n\r\n - Series\r\n - DataFrame\r\n - SeriesGroupBy\r\n - DataFrameGroupBy\r\n - Window\r\n - Resample","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46560/reactions","total_count":1,"+1":1,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46560/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46554","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46554/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46554/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46554/events","html_url":"https://github.com/pandas-dev/pandas/issues/46554","id":1184575321,"node_id":"I_kwDOAA0YD85Gmy9Z","number":46554,"title":"QST: mypy errors when extending pandas Series with custom mixin","user":{"login":"verdimrc","id":2340781,"node_id":"MDQ6VXNlcjIzNDA3ODE=","avatar_url":"https://avatars.githubusercontent.com/u/2340781?v=4","gravatar_id":"","url":"https://api.github.com/users/verdimrc","html_url":"https://github.com/verdimrc","followers_url":"https://api.github.com/users/verdimrc/followers","following_url":"https://api.github.com/users/verdimrc/following{/other_user}","gists_url":"https://api.github.com/users/verdimrc/gists{/gist_id}","starred_url":"https://api.github.com/users/verdimrc/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/verdimrc/subscriptions","organizations_url":"https://api.github.com/users/verdimrc/orgs","repos_url":"https://api.github.com/users/verdimrc/repos","events_url":"https://api.github.com/users/verdimrc/events{/privacy}","received_events_url":"https://api.github.com/users/verdimrc/received_events","type":"User","site_admin":false},"labels":[{"id":307649777,"node_id":"MDU6TGFiZWwzMDc2NDk3Nzc=","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info","name":"Needs Info","color":"207de5","default":false,"description":"Clarification about behavior needed to assess issue"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pandas-dev/pandas/milestones/33","html_url":"https://github.com/pandas-dev/pandas/milestone/33","labels_url":"https://api.github.com/repos/pandas-dev/pandas/milestones/33/labels","id":997544,"node_id":"MDk6TWlsZXN0b25lOTk3NTQ0","number":33,"title":"No action","description":"A milestone for closed or open issues for which there is no action needed (eg not a bug, just a question / discussion, nothing to resolve, wontfix, etc).\r\n\r\n","creator":{"login":"jorisvandenbossche","id":1020496,"node_id":"MDQ6VXNlcjEwMjA0OTY=","avatar_url":"https://avatars.githubusercontent.com/u/1020496?v=4","gravatar_id":"","url":"https://api.github.com/users/jorisvandenbossche","html_url":"https://github.com/jorisvandenbossche","followers_url":"https://api.github.com/users/jorisvandenbossche/followers","following_url":"https://api.github.com/users/jorisvandenbossche/following{/other_user}","gists_url":"https://api.github.com/users/jorisvandenbossche/gists{/gist_id}","starred_url":"https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jorisvandenbossche/subscriptions","organizations_url":"https://api.github.com/users/jorisvandenbossche/orgs","repos_url":"https://api.github.com/users/jorisvandenbossche/repos","events_url":"https://api.github.com/users/jorisvandenbossche/events{/privacy}","received_events_url":"https://api.github.com/users/jorisvandenbossche/received_events","type":"User","site_admin":false},"open_issues":11,"closed_issues":2424,"state":"open","created_at":"2015-02-26T19:29:05Z","updated_at":"2022-03-30T07:23:45Z","due_on":null,"closed_at":null},"comments":4,"created_at":"2022-03-29T09:29:08Z","updated_at":"2022-03-31T09:16:44Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Research\n\n- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.\n\n- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).\n\n\n### Link to question on StackOverflow\n\nhttps://stackoverflow.com/questions/71649892/mypy-errors-when-extending-pandas-series\n\n### Question about pandas\n\nHi,\r\n\r\nI encountered mypy errors `Definition of \"_values\" in base class \"IndexOpsMixin\" is incompatible with definition in base class \"NDFrame\"` when [extending](https://pandas.pydata.org/docs/development/extending.html#subclassing-pandas-data-structures) pandas Series.\r\n\r\nThe error disappears when `MyMixin` is removed from `SubclassedSeries`'s parent. However, I'd like to keep the mixin to provide common functions for both `SubclassedSeries` and `SubclassedDataFrame`, and I wonder what changes needed to remove the mypy errors?\r\n\r\n```python\r\nimport pandas as pd\r\n\r\n\r\nclass MyMixin:\r\n    def common_function(self):\r\n        return 123\r\n\r\n\r\nclass SubclassedSeries(MyMixin, pd.Series):  # <-- Mypy errors.\r\n    @property\r\n    def _constructor(self):\r\n        return SubclassedSeries\r\n\r\n    @property\r\n    def _constructor_expanddim(self):\r\n        return SubclassedDataFrame\r\n\r\n\r\nclass SubclassedDataFrame(MyMixin, pd.DataFrame):\r\n    @property\r\n    def _constructor(self):\r\n        return SubclassedDataFrame\r\n\r\n    @property\r\n    def _constructor_sliced(self):\r\n        return SubclassedSeries\r\n```\r\n\r\n```bash\r\n$ mypy mydf.py\r\nmydf.py:9: error: Definition of \"_values\" in base class \"IndexOpsMixin\" is incompatible with definition in base class \"NDFrame\"\r\nFound 1 error in 1 file (checked 1 source file)\r\n```\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46554/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46554/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46553","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46553/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46553/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46553/events","html_url":"https://github.com/pandas-dev/pandas/issues/46553","id":1184482464,"node_id":"I_kwDOAA0YD85GmcSg","number":46553,"title":"ENH: Compact result from named aggregation","user":{"login":"kwhkim","id":4476168,"node_id":"MDQ6VXNlcjQ0NzYxNjg=","avatar_url":"https://avatars.githubusercontent.com/u/4476168?v=4","gravatar_id":"","url":"https://api.github.com/users/kwhkim","html_url":"https://github.com/kwhkim","followers_url":"https://api.github.com/users/kwhkim/followers","following_url":"https://api.github.com/users/kwhkim/following{/other_user}","gists_url":"https://api.github.com/users/kwhkim/gists{/gist_id}","starred_url":"https://api.github.com/users/kwhkim/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kwhkim/subscriptions","organizations_url":"https://api.github.com/users/kwhkim/orgs","repos_url":"https://api.github.com/users/kwhkim/repos","events_url":"https://api.github.com/users/kwhkim/events{/privacy}","received_events_url":"https://api.github.com/users/kwhkim/received_events","type":"User","site_admin":false},"labels":[{"id":76812,"node_id":"MDU6TGFiZWw3NjgxMg==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement","name":"Enhancement","color":"4E9A06","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-29T08:13:02Z","updated_at":"2022-03-29T08:13:02Z","closed_at":null,"author_association":"CONTRIBUTOR","active_lock_reason":null,"body":"#### Is your feature request related to a problem?\r\n\r\n```python\r\ndat = pd.DataFrame({'carat':[0.23, 0.21, 0.23, 0.29, 0.31],\r\n                    'x':[3.95, 3.89, 4.05, 4.20, 4.34]},\r\n                  index = [1,2,3,4,5])\r\ndat.agg(mean1 = ('carat', 'mean'), stdx = ('x', np.std))\r\n## \tcarat\tx\r\n## mean1\t0.254\tNaN\r\n## stdx\tNaN\t0.184201\r\n\r\ndat.agg({'carat':'mean', 'x':'std'})\r\n## carat    0.254000\r\n## x        0.184201\r\n## dtype: float64\r\n```\r\n\r\nFor consistency, result of `dat.agg(meanx = ('carat', 'mean'), stdx = ('x', np.std))` should better be \r\n```python\r\n## meanx    0.254000\r\n## stdx        0.184201\r\n## dtype: float64\r\n```\r\n\r\nAnyway putting `NaN`'s does not help anyone here. Take a look at the code below\r\n\r\n```python\r\ndat.agg(mean1 = ('carat', 'mean'), std = ('x', 'std'), mean3 = ('carat', 'std'))\r\n## \tcarat\tx\r\n## mean1\t0.254000\tNaN\r\n## std\tNaN\t0.184201\r\n## mean3\t0.043359\tNaN\r\n```\r\n\r\nso even if we used the same 'std' function, there is no way we can name the index 'std'  for the result twice,\r\nbecause index name is function parameter name(function can not have two identical parameter name)\r\n\r\nCompare the result below with the result above.\r\n\r\n```python\r\ndat.agg({'carat':['mean', 'std'], 'x':['std', 'var']})\r\n\t  carat\tx\r\n## mean\t0.254000\tNaN\r\n## std\t0.043359\t0.184201\r\n## var\tNaN\t0.033930\r\n```\r\n\r\nIt might better to support something like the below\r\n\r\n```python\r\ndat.agg(f1 = ('carat', ('mean', 'std')), f2 = ('x', (np.std, 'var')))\r\n\t  f1          f2\r\n## mean\t0.254000\tNaN\r\n## std\t0.043359\t0.184201\r\n## var\tNaN\t0.033930\r\n\r\n```\r\n\r\n#### Describe the solution you'd like\r\n\r\nFor consistency, result of `dat.agg(mean = ('carat', 'mean'), std = ('x', np.std))` should better be \r\n```python\r\n## mean    0.254000\r\n## std        0.184201\r\n## dtype: float64\r\n```\r\n\r\nand \r\n\r\nIt might better to support something like the below\r\n\r\n```python\r\ndat.agg(v1 = ('carat', ('mean', 'std')), v2 = ('x', (np.std, 'var')))\r\n\t  v1          v2\r\n## mean\t0.254000\tNaN\r\n## std\t0.043359\t0.184201\r\n## var\tNaN\t0.033930\r\n```\r\n\r\n#### API breaking implications\r\n\r\n[this should provide a description of how this feature will affect the API]\r\n\r\nThere is not much inconsistency nor contradiction from this change.\r\n\r\n#### Describe alternatives you've considered\r\n\r\n[this should provide a description of any alternative solutions or features you've considered]\r\n\r\nI can't think of any now\r\n\r\n#### Additional context\r\n\r\n[add any other context, code examples, or references to existing implementations about the feature request here]\r\n\r\n\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46553/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46553/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46552","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46552/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46552/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46552/events","html_url":"https://github.com/pandas-dev/pandas/issues/46552","id":1184197156,"node_id":"I_kwDOAA0YD85GlWok","number":46552,"title":"BUG:  Unexpected change of behavior on DataFrame type float32 between pandas versions.","user":{"login":"carlosan1708","id":15173842,"node_id":"MDQ6VXNlcjE1MTczODQy","avatar_url":"https://avatars.githubusercontent.com/u/15173842?v=4","gravatar_id":"","url":"https://api.github.com/users/carlosan1708","html_url":"https://github.com/carlosan1708","followers_url":"https://api.github.com/users/carlosan1708/followers","following_url":"https://api.github.com/users/carlosan1708/following{/other_user}","gists_url":"https://api.github.com/users/carlosan1708/gists{/gist_id}","starred_url":"https://api.github.com/users/carlosan1708/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/carlosan1708/subscriptions","organizations_url":"https://api.github.com/users/carlosan1708/orgs","repos_url":"https://api.github.com/users/carlosan1708/repos","events_url":"https://api.github.com/users/carlosan1708/events{/privacy}","received_events_url":"https://api.github.com/users/carlosan1708/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":307649777,"node_id":"MDU6TGFiZWwzMDc2NDk3Nzc=","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info","name":"Needs Info","color":"207de5","default":false,"description":"Clarification about behavior needed to assess issue"},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2022-03-29T02:03:29Z","updated_at":"2022-03-30T17:48:32Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\nimport numpy as np\r\nimport json\r\n\r\ndef check_error(x, r):\r\n    df = pd.DataFrame(data=x, dtype=\"float32\")\r\n    for i in df.index:\r\n        for j in range(len(list(df.iloc[i]))):\r\n            # Here is the difference, it\"s converting str to float32 in pandas 1.3.5\r\n            # On pandas 1.4.0 no longer happens, instead it's keeping the value intact.\r\n            df.iloc[i][j] = r[j][int(df.iloc[i][j])]\r\n    return df\r\n\r\n\r\nx = [[0, 0.], [1., 0.], [0., 1.], [1., 1.]]\r\nr = np.array([[\"10\", \"20\"], [\"50\", \"40\"]])\r\n\r\nresult = check_error(x, r).to_json()\r\nresult_json = expected = json.loads(result)\r\n## Pandas 1.3.5\r\nif pd.__version__==\"1.3.5\":\r\n    expected_json_pandas_1_3_5 = json.loads(\"\"\"\r\n    {\"0\":{\"0\":10.0,\"1\":20.0,\"2\":10.0,\"3\":20.0},\"1\":{\"0\":50.0,\"1\":50.0,\"2\":40.0,\"3\":40.0}}\r\n    \"\"\")\r\n    print(sorted(result_json.items()) == sorted(expected_json_pandas_1_3_5.items()))\r\nelse:\r\n    expected_json_pandas_1_4_0 = json.loads(\"\"\"\r\n    {\"0\": {\"0\": 0.0, \"1\": 1.0, \"2\": 0.0, \"3\": 1.0}, \"1\": {\"0\": 0.0, \"1\": 0.0, \"2\": 1.0, \"3\": 1.0}}\r\n    \"\"\")\r\n    ## Pandas 1.4.0\r\n    print(sorted(result_json.items()) == sorted(expected_json_pandas_1_4_0.items()))\n```\n\n\n### Issue Description\n\nThere is a change of behavior that is not mentioned in the documentation that could cause issues in existing libraries when assigning variables in a data frame with float32, I haven't checked if in other types of data frames the same could occur.\r\n\r\nPretty when using data frames with type float32 the assignation is not reacting in the same way between 1.3.5 pandas version and 1.4.0. In 1.3.5 str type is getting transformed into a float type, in 1.4.0 this is no longer occurring and instead, the assignation is not occurring anymore, but this is not throwing an error either which is causing as in the example two data frames to contain different information based on pandas version.\n\n### Expected Behavior\n\nChange should be called out in the documentation of 1.4.0 or throw an error instead to alert users about incorrect types during the assignation of variables. Overall it might be worthy to explore if this is not affecting other dataframes types. \n\n### Installed Versions\n\n<details>\r\n\r\nPandas 1.3.5 \r\n\r\nPandas 1.4.0\r\n\r\nPandas 1.4.1\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46552/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46552/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46551","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46551/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46551/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46551/events","html_url":"https://github.com/pandas-dev/pandas/issues/46551","id":1184130581,"node_id":"I_kwDOAA0YD85GlGYV","number":46551,"title":"BUG: Unexpected IndexingError when filtering with .loc","user":{"login":"bikoboshi","id":72529861,"node_id":"MDQ6VXNlcjcyNTI5ODYx","avatar_url":"https://avatars.githubusercontent.com/u/72529861?v=4","gravatar_id":"","url":"https://api.github.com/users/bikoboshi","html_url":"https://github.com/bikoboshi","followers_url":"https://api.github.com/users/bikoboshi/followers","following_url":"https://api.github.com/users/bikoboshi/following{/other_user}","gists_url":"https://api.github.com/users/bikoboshi/gists{/gist_id}","starred_url":"https://api.github.com/users/bikoboshi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bikoboshi/subscriptions","organizations_url":"https://api.github.com/users/bikoboshi/orgs","repos_url":"https://api.github.com/users/bikoboshi/repos","events_url":"https://api.github.com/users/bikoboshi/events{/privacy}","received_events_url":"https://api.github.com/users/bikoboshi/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":2822098,"node_id":"MDU6TGFiZWwyODIyMDk4","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Indexing","name":"Indexing","color":"0b02e1","default":false,"description":"Related to indexing on series/frames, not to indexes themselves"}],"state":"open","locked":false,"assignee":{"login":"mctessi","id":100441021,"node_id":"U_kgDOBfybvQ","avatar_url":"https://avatars.githubusercontent.com/u/100441021?v=4","gravatar_id":"","url":"https://api.github.com/users/mctessi","html_url":"https://github.com/mctessi","followers_url":"https://api.github.com/users/mctessi/followers","following_url":"https://api.github.com/users/mctessi/following{/other_user}","gists_url":"https://api.github.com/users/mctessi/gists{/gist_id}","starred_url":"https://api.github.com/users/mctessi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mctessi/subscriptions","organizations_url":"https://api.github.com/users/mctessi/orgs","repos_url":"https://api.github.com/users/mctessi/repos","events_url":"https://api.github.com/users/mctessi/events{/privacy}","received_events_url":"https://api.github.com/users/mctessi/received_events","type":"User","site_admin":false},"assignees":[{"login":"mctessi","id":100441021,"node_id":"U_kgDOBfybvQ","avatar_url":"https://avatars.githubusercontent.com/u/100441021?v=4","gravatar_id":"","url":"https://api.github.com/users/mctessi","html_url":"https://github.com/mctessi","followers_url":"https://api.github.com/users/mctessi/followers","following_url":"https://api.github.com/users/mctessi/following{/other_user}","gists_url":"https://api.github.com/users/mctessi/gists{/gist_id}","starred_url":"https://api.github.com/users/mctessi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mctessi/subscriptions","organizations_url":"https://api.github.com/users/mctessi/orgs","repos_url":"https://api.github.com/users/mctessi/repos","events_url":"https://api.github.com/users/mctessi/events{/privacy}","received_events_url":"https://api.github.com/users/mctessi/received_events","type":"User","site_admin":false}],"milestone":null,"comments":6,"created_at":"2022-03-29T00:09:43Z","updated_at":"2022-03-31T18:48:32Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\n>>> a = pd.Series([True, False])\r\n>>> b = pd.Series([np.nan, False]).astype('boolean')\r\n>>> s = pd.Series([1,2])\r\n>>> s.loc[a].loc[b]\r\n...\r\npandas.core.indexing.IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nThe example throws an unexpected indexing error. The error seems to trigger if the first filter is neither the identity nor empty and when combined with the second filter with nan is empty. The error does not seem to trigger otherwise.\r\n\r\n### Expected Behavior\r\n\r\nI expect this identity to hold `s.loc[a].loc[b] == s.loc[b].loc[a] == s.loc[a & b]` which it does except for the exception above.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d\r\npython           : 3.7.2.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.22000\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.None\r\n\r\npandas           : 1.3.5\r\nnumpy            : 1.17.4\r\npytz             : 2019.1\r\ndateutil         : 2.8.0\r\npip              : 21.2.4\r\nsetuptools       : 46.0.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.10\r\nIPython          : 7.8.0\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : 3.1.1\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : 1.3.5\r\ntables           : None\r\ntabulate         : 0.8.3\r\nxarray           : None\r\nxlrd             : 1.2.0\r\nxlwt             : None\r\nnumba            : None\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46551/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46551/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46549","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46549/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46549/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46549/events","html_url":"https://github.com/pandas-dev/pandas/issues/46549","id":1184051642,"node_id":"I_kwDOAA0YD85GkzG6","number":46549,"title":"BUG: MultiIndex KeyError message unreliable","user":{"login":"kwsp","id":30088608,"node_id":"MDQ6VXNlcjMwMDg4NjA4","avatar_url":"https://avatars.githubusercontent.com/u/30088608?v=4","gravatar_id":"","url":"https://api.github.com/users/kwsp","html_url":"https://github.com/kwsp","followers_url":"https://api.github.com/users/kwsp/followers","following_url":"https://api.github.com/users/kwsp/following{/other_user}","gists_url":"https://api.github.com/users/kwsp/gists{/gist_id}","starred_url":"https://api.github.com/users/kwsp/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kwsp/subscriptions","organizations_url":"https://api.github.com/users/kwsp/orgs","repos_url":"https://api.github.com/users/kwsp/repos","events_url":"https://api.github.com/users/kwsp/events{/privacy}","received_events_url":"https://api.github.com/users/kwsp/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-28T22:11:32Z","updated_at":"2022-03-28T22:17:33Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\n\r\n# Expected\r\ndf = pd.DataFrame({(\"x\", \"x\"): [1]})\r\ndf[(\"x\", \"y\")] # throws KeyError: ('x', 'y')\r\n\r\n# Bug\r\ndf = pd.DataFrame({(\"x\", \"x\"): [1], (\"y\", \"y\"): [1]})\r\ndf[(\"x\", \"y\")]  # throws KeyError: 6\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nNormally when indexing with a key that doesn't exist, Pandas throws a `KeyError` with the value of the key printed in the exception string.\r\n\r\nWhen using `MultiIndex` as the column key and trying to index with a non-existent key, sometimes the `KeyError` throws the right name, sometimes it does not, which makes the error message arcane and difficult to debug. \r\n\r\n### Expected Behavior\r\n\r\nWhen indexing with a key that doesn't exist, Pandas should always print the value of the key when throwing a `KeyError`. I.e. both examples above should throw `KeyError: ('x', 'y')`\r\n\r\n### Installed Versions\r\n\r\nmacOS\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.10.1.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 21.1.0\r\nVersion          : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101\r\nmachine          : arm64\r\nprocessor        : arm\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.21.5\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 22.0.3\r\nsetuptools       : 59.5.0\r\nCython           : 0.29.28\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.8.0\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.1.0\r\npandas_datareader: None\r\nbs4              : 4.10.0\r\nbottleneck       : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.8.0\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>\r\n\r\nWindows\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.10.0.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19042\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 165 Stepping 5, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.22.3\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 58.0.4\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.1.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.7.3\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46549/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46549/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46546","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46546/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46546/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46546/events","html_url":"https://github.com/pandas-dev/pandas/pull/46546","id":1183908098,"node_id":"PR_kwDOAA0YD841Lipq","number":46546,"title":"BUG: pd.concat with identical key leads to multi-indexing error","user":{"login":"GYHHAHA","id":41546976,"node_id":"MDQ6VXNlcjQxNTQ2OTc2","avatar_url":"https://avatars.githubusercontent.com/u/41546976?v=4","gravatar_id":"","url":"https://api.github.com/users/GYHHAHA","html_url":"https://github.com/GYHHAHA","followers_url":"https://api.github.com/users/GYHHAHA/followers","following_url":"https://api.github.com/users/GYHHAHA/following{/other_user}","gists_url":"https://api.github.com/users/GYHHAHA/gists{/gist_id}","starred_url":"https://api.github.com/users/GYHHAHA/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/GYHHAHA/subscriptions","organizations_url":"https://api.github.com/users/GYHHAHA/orgs","repos_url":"https://api.github.com/users/GYHHAHA/repos","events_url":"https://api.github.com/users/GYHHAHA/events{/privacy}","received_events_url":"https://api.github.com/users/GYHHAHA/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":13098779,"node_id":"MDU6TGFiZWwxMzA5ODc3OQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping","name":"Reshaping","color":"02d7e1","default":false,"description":"Concat, Merge/Join, Stack/Unstack, Explode"},{"id":71268330,"node_id":"MDU6TGFiZWw3MTI2ODMzMA==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex","name":"MultiIndex","color":"207de5","default":false,"description":null}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":{"url":"https://api.github.com/repos/pandas-dev/pandas/milestones/92","html_url":"https://github.com/pandas-dev/pandas/milestone/92","labels_url":"https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels","id":7530006,"node_id":"MI_kwDOAA0YD84AcuYW","number":92,"title":"1.5","description":"","creator":{"login":"jreback","id":953992,"node_id":"MDQ6VXNlcjk1Mzk5Mg==","avatar_url":"https://avatars.githubusercontent.com/u/953992?v=4","gravatar_id":"","url":"https://api.github.com/users/jreback","html_url":"https://github.com/jreback","followers_url":"https://api.github.com/users/jreback/followers","following_url":"https://api.github.com/users/jreback/following{/other_user}","gists_url":"https://api.github.com/users/jreback/gists{/gist_id}","starred_url":"https://api.github.com/users/jreback/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jreback/subscriptions","organizations_url":"https://api.github.com/users/jreback/orgs","repos_url":"https://api.github.com/users/jreback/repos","events_url":"https://api.github.com/users/jreback/events{/privacy}","received_events_url":"https://api.github.com/users/jreback/received_events","type":"User","site_admin":false},"open_issues":53,"closed_issues":600,"state":"open","created_at":"2021-12-31T21:51:13Z","updated_at":"2022-03-31T17:59:23Z","due_on":"2022-06-30T07:00:00Z","closed_at":null},"comments":1,"created_at":"2022-03-28T19:47:50Z","updated_at":"2022-03-31T19:12:49Z","closed_at":null,"author_association":"CONTRIBUTOR","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/46546","html_url":"https://github.com/pandas-dev/pandas/pull/46546","diff_url":"https://github.com/pandas-dev/pandas/pull/46546.diff","patch_url":"https://github.com/pandas-dev/pandas/pull/46546.patch","merged_at":null},"body":"- [x] closes #46519 \r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46546/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46546/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46544","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46544/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46544/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46544/events","html_url":"https://github.com/pandas-dev/pandas/issues/46544","id":1183850935,"node_id":"I_kwDOAA0YD85GkCG3","number":46544,"title":"BUG: `DataFrame.loc` is not consistent with `DataFrame.__setitem__` when used with 2D numpy array","user":{"login":"anmyachev","id":45976948,"node_id":"MDQ6VXNlcjQ1OTc2OTQ4","avatar_url":"https://avatars.githubusercontent.com/u/45976948?v=4","gravatar_id":"","url":"https://api.github.com/users/anmyachev","html_url":"https://github.com/anmyachev","followers_url":"https://api.github.com/users/anmyachev/followers","following_url":"https://api.github.com/users/anmyachev/following{/other_user}","gists_url":"https://api.github.com/users/anmyachev/gists{/gist_id}","starred_url":"https://api.github.com/users/anmyachev/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/anmyachev/subscriptions","organizations_url":"https://api.github.com/users/anmyachev/orgs","repos_url":"https://api.github.com/users/anmyachev/repos","events_url":"https://api.github.com/users/anmyachev/events{/privacy}","received_events_url":"https://api.github.com/users/anmyachev/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":2822098,"node_id":"MDU6TGFiZWwyODIyMDk4","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Indexing","name":"Indexing","color":"0b02e1","default":false,"description":"Related to indexing on series/frames, not to indexes themselves"},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2022-03-28T18:52:30Z","updated_at":"2022-03-30T17:09:25Z","closed_at":null,"author_association":"CONTRIBUTOR","active_lock_reason":null,"body":"### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [ ] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\nimport numpy as np\r\n\r\ndf = pd.DataFrame(np.zeros((256, 10)))\r\narray_2d = np.zeros((256, 2))\r\n\r\ndf[0] = array_2d  # works\r\ndf[\"col33\"] = array_2d  # raises exception, see #46545\r\ndf.loc[:,0] = array_2d  # *** ValueError: Must have equal len keys and value when setting with an ndarray\r\n# Note: if you swap 2 lines from above, then the code will work!\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nInconsistent behavior of functions that should behave the same.\r\n\r\n### Expected Behavior\r\n\r\nEither an exception should be thrown for both cases, or it should not, but also in both cases.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.8.12.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19044\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.22.2\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 22.0.3\r\nsetuptools       : 59.8.0\r\nCython           : None\r\npytest           : 7.0.0\r\nhypothesis       : None\r\nsphinx           : 4.4.0\r\nblosc            : None\r\nfeather          : 0.4.1\r\nxlsxwriter       : None\r\nlxml.etree       : 4.7.1\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.0.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\nfsspec           : 2022.01.0\r\ngcsfs            : None\r\nmatplotlib       : 3.2.2\r\nnumba            : None\r\nnumexpr          : 2.7.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : 0.17.0\r\npyarrow          : 6.0.1\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : 2022.01.0\r\nscipy            : 1.8.0\r\nsqlalchemy       : 1.4.31\r\ntables           : 3.7.0\r\ntabulate         : None\r\nxarray           : 0.21.1\r\nxlrd             : 2.0.1\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46544/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46544/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46539","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46539/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46539/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46539/events","html_url":"https://github.com/pandas-dev/pandas/issues/46539","id":1183317929,"node_id":"I_kwDOAA0YD85Gh_-p","number":46539,"title":"BUG: pd.concat on DF with time series containing daylight/non-daylight savings times changes some time index values and sets data values to NaN","user":{"login":"davehemming","id":6355796,"node_id":"MDQ6VXNlcjYzNTU3OTY=","avatar_url":"https://avatars.githubusercontent.com/u/6355796?v=4","gravatar_id":"","url":"https://api.github.com/users/davehemming","html_url":"https://github.com/davehemming","followers_url":"https://api.github.com/users/davehemming/followers","following_url":"https://api.github.com/users/davehemming/following{/other_user}","gists_url":"https://api.github.com/users/davehemming/gists{/gist_id}","starred_url":"https://api.github.com/users/davehemming/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davehemming/subscriptions","organizations_url":"https://api.github.com/users/davehemming/orgs","repos_url":"https://api.github.com/users/davehemming/repos","events_url":"https://api.github.com/users/davehemming/events{/privacy}","received_events_url":"https://api.github.com/users/davehemming/received_events","type":"User","site_admin":false},"labels":[{"id":76811,"node_id":"MDU6TGFiZWw3NjgxMQ==","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Bug","name":"Bug","color":"e10c02","default":false,"description":null},{"id":1954720290,"node_id":"MDU6TGFiZWwxOTU0NzIwMjkw","url":"https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage","name":"Needs Triage","color":"0052cc","default":false,"description":"Issue that has not been reviewed by a pandas team member"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2022-03-28T11:47:51Z","updated_at":"2022-03-28T11:55:50Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pytz\r\nimport numpy as np\r\nimport pandas as pd\r\nfrom datetime import datetime\r\nlocal_tz = pytz.timezone(\"Australia/Melbourne\")\r\nmin_df = pd.DataFrame({\"low\": np.round(np.linspace(2., 4., num=10), 2)}, index=pd.date_range(local_tz.localize(datetime.fromisoformat(\"2022-03-26T00:00:00\")), periods=10, name=\"localTime\"))\r\nmax_df = pd.DataFrame({\"low\": np.round(np.linspace(6., 8., num=11), 2)}, index=pd.date_range(local_tz.localize(datetime.fromisoformat(\"2022-03-25T00:00:00\")), periods=11, name=\"localTime\"))\r\npd.concat([min_df, max_df], axis=1)\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nGiven a DataFrame that has a time series index that starts on the `26-03-2022` and finishes on the `04-04-2022` and another DataFrame that starts a day prior on the `25-03-2022` and finishes on the same day `04-04-2022` and the timezone for the index of both these DataFrame's is localized to `Australia/Melbourne` time which will have a DST End event  `03-04-2022T03:00:00` where clocks go back an hour and one DF contains min temperature values and another contain max temperature values when I do `pd.concat([min_df, max_df], axis=1)` then I get a result where the last two records have had their time values changed, and there data values are now NaN and the last min and max values are replaced with NaN and there is a duplicate row for the same day with a different time.  This is the result you get:\r\n\r\n```\r\n                            low  low\r\nlocalTime\r\n2022-03-25 00:00:00+11:00   NaN  6.0\r\n2022-03-26 00:00:00+11:00  2.00  6.2\r\n2022-03-27 00:00:00+11:00  2.22  6.4\r\n2022-03-28 00:00:00+11:00  2.44  6.6\r\n2022-03-29 00:00:00+11:00  2.67  6.8\r\n2022-03-30 00:00:00+11:00  2.89  7.0\r\n2022-03-31 00:00:00+11:00  3.11  7.2\r\n2022-04-01 00:00:00+11:00  3.33  7.4\r\n2022-04-02 00:00:00+11:00  3.56  7.6\r\n2022-04-03 00:00:00+11:00  3.78  7.8\r\n2022-04-03 23:00:00+10:00   NaN  NaN\r\n2022-04-04 23:00:00+10:00   NaN  NaN\r\n```\r\n\r\nIf you change the timezone to \"Australia/Brisbane\" that is not about to have a timezone change then the result is as expected.\r\nIf you install the pandas version `1.3.5` and run the supplied sample you get the expected result.\r\n\r\n### Expected Behavior\r\n\r\n`pd.concat([min_df, max_df], axis=1)`\r\n\r\n```\r\n                            low  low\r\nlocalTime\r\n2022-03-25 00:00:00+11:00   NaN  6.0\r\n2022-03-26 00:00:00+11:00  2.00  6.2\r\n2022-03-27 00:00:00+11:00  2.22  6.4\r\n2022-03-28 00:00:00+11:00  2.44  6.6\r\n2022-03-29 00:00:00+11:00  2.67  6.8\r\n2022-03-30 00:00:00+11:00  2.89  7.0\r\n2022-03-31 00:00:00+11:00  3.11  7.2\r\n2022-04-01 00:00:00+11:00  3.33  7.4\r\n2022-04-02 00:00:00+11:00  3.56  7.6\r\n2022-04-03 00:00:00+11:00  3.78  7.8\r\n2022-04-04 00:00:00+10:00  4.00  8.0\r\n```\r\n\r\n### Installed Versions\r\n\r\nWhen running `pd.show_versions()` I was getting:\r\n\r\n```\r\nAssertionError: /opt/anaconda3/envs/jw-met-data-transformer/lib/python3.8/distutils/core.py\r\n```\r\n\r\n<details>\r\n\r\n1.4.1\r\n\r\n</details>\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46539/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46539/timeline","performed_via_github_app":null},{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46538","repository_url":"https://api.github.com/repos/pandas-dev/pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46538/labels{/name}","comments_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46538/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46538/events","html_url":"https://github.com/pandas-dev/pandas/pull/46538","id":1183041719,"node_id":"PR_kwDOAA0YD841Iq-a","number":46538,"title":"CI: Refactor sdist workflow and add setup-python action","user":{"login":"jonashaag","id":175722,"node_id":"MDQ6VXNlcjE3NTcyMg==","avatar_url":"https://avatars.githubusercontent.com/u/175722?v=4","gravatar_id":"","url":"https://api.github.com/users/jonashaag","html_url":"https://github.com/jonashaag","followers_url":"https://api.github.com/users/jonashaag/followers","following_url":"https://api.github.com/users/jonashaag/following{/other_user}","gists_url":"https://api.github.com/users/jonashaag/gists{/gist_id}","starred_url":"https://api.github.com/users/jonashaag/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jonashaag/subscriptions","organizations_url":"https://api.github.com/users/jonashaag/orgs","repos_url":"https://api.github.com/users/jonashaag/repos","events_url":"https://api.github.com/users/jonashaag/events{/privacy}","received_events_url":"https://api.github.com/users/jonashaag/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2022-03-28T07:57:06Z","updated_at":"2022-03-30T09:03:53Z","closed_at":null,"author_association":"CONTRIBUTOR","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/pandas-dev/pandas/pulls/46538","html_url":"https://github.com/pandas-dev/pandas/pull/46538","diff_url":"https://github.com/pandas-dev/pandas/pull/46538.diff","patch_url":"https://github.com/pandas-dev/pandas/pull/46538.patch","merged_at":null},"body":"Smaller version of https://github.com/pandas-dev/pandas/pull/46493 according to suggestion in https://github.com/pandas-dev/pandas/pull/46493#issuecomment-1079541210\r\n\r\n- [ ] closes #xxxx (Replace xxxx with the Github issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n","reactions":{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/46538/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/pandas-dev/pandas/issues/46538/timeline","performed_via_github_app":null}]